### ISSUE TITLE
Monitoring admin_console: batch execution failed

### ISSUE THREAD

**Issue by mariamartinciviac** [kaltura/platform-install-packages#227]
Hi,

I succesfully installed Kaltura on my server (http://fisvideo.fis-ski.com/start/index.php) but seems like the /opt/kaltura/log/batch/batch.pid failed to execute as I notified under the admin_console-> monitoring.

This issue apparently affects the user management tool as no matter who I register, wouldnt get an email to set up their passwords. Besides, the content section is also affected as the upload video would be always "converting" status and it is always also "in queue", it never goes "ready"

I would really appreaciate any hint/guidance on it. When loading the KMC, always gives an internal error message which is shown in the kaltlog as follows:

2014-09-16 11:27:05 [0.000615] [192.168.0.180] [91591640] [API] [myReportsMgr::executeQuery] NOTICE: Reports query using database host: [127.0.0.1] user [etl]
2014-09-16 11:27:05 [0.000507] [192.168.0.180] [91591640] [API] [myReportsMgr::executeQuery] ERR: exception 'Exception' with message 'Invalid query: PROCEDURE kalturadw.calc_partner_usage_data does not exist' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:
#0 /opt/kaltura/app/alpha/apps/kaltura/lib/reports/myReportsMgr.class.php(1200): KalturaLog::err('Invalid query: ...')
## 
#11 {main}

2014-09-16 11:27:05 [0.000373] [192.168.0.180] [91591640] [API] [kCoreException->__construct] ERR: exception 'kCoreException' with message 'Invalid query' in /opt/kaltura/app/alpha/apps/kaltura/lib/reports/myReportsMgr.class.php:1202
Stack trace:
#0 /opt/kaltura/app/alpha/apps/kaltura/lib/reports/myReportsMgr.class.php(763): myReportsMgr::executeQuery('?CALL kalturadw...')
## 

2014-09-16 11:27:05 [0.000225] [192.168.0.180] [91591640] [API] [myReportsMgr::executeQueryByType] NOTICE: Invalid query
2014-09-16 11:27:05 [0.000416] [192.168.0.180] [91591640] [API] [KalturaFrontController->getExceptionObject] CRIT: exception 'kCoreException' with message 'Invalid query' in /opt/kaltura/app/alpha/apps/kaltura/lib/reports/myReportsMgr.class.php:1202
Stack trace:
#0 /opt/kaltura/app/alpha/apps/kaltura/lib/reports/myReportsMgr.class.php(763): myReportsMgr::executeQuery('?CALL kalturadw...')
## 

2014-09-16 11:28:10 [1037189061] [KSchedulerConfig->load] NOTICE: loading configuration /opt/kaltura/app/configurations/batch at 1410459347
PHP Fatal error:  Uncaught exception 'Zend_Config_Exception' with message 'Section 'fisvideo' cannot be found in /opt/kaltura/app/cache//batch/config.ini' in /opt/kaltura/app/vendor/ZendFramework/library/Zend/Config/Ini.php:150
Stack trace:
#0 /opt/kaltura/app/batch/scheduler/KSchedulerConfig.class.php(59): Zend_Config_Ini->__construct('/opt/kaltura/ap...', 'fisvideo', true)

**Comment by jessp01** [comment]
Most wekcome. So all is well? If so please close.


May the source be with you,

Jess Portnoy



-------- Original message --------
