### ISSUE TITLE
Blank page Kaltura KMC

### ISSUE THREAD

**Issue by Atheryl** [kaltura/platform-install-packages#324]
Hi,

 I did my 10th install on CentOS 6.6 with version 10.2.0. Of course I did read many topic about it but didn't find solution (I succeed make this part work in a previous try but something else was broken ...).

 Everything is fine during installation, everything is working well, I can access the admin console working fine, except some logs (below)

#6 {main}
2015-01-14 12:28:32 [861271409] [InfraBootstrapper->_initNavigation] ERR: exception 'Exception' with message 'Class [DropFolderConfigureAction] requires permissions [Array
(
--
]' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:
#0 /opt/kaltura/app/ui_infra/InfraBootstrapper.php(113): KalturaLog::err('Class [DropFold...')
--
#6 {main}
2015-01-14 12:28:32 [861271409] [InfraBootstrapper->_initNavigation] ERR: exception 'Exception' with message 'Class [DropFolderSetStatusAction] requires permissions [Array
(
--
]' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:
#0 /opt/kaltura/app/ui_infra/InfraBootstrapper.php(113): KalturaLog::err('Class [DropFold...')
--
#6 {main}
2015-01-14 12:28:32 [861271409] [InfraBootstrapper->_initNavigation] ERR: exception 'Exception' with message 'Class [EventNotificationTemplatesListAction] requires permissions [Array
(
--
]' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:
#0 /opt/kaltura/app/ui_infra/InfraBootstrapper.php(113): KalturaLog::err('Class [EventNot...')
--
#6 {main}
2015-01-14 12:28:32 [861271409] [InfraBootstrapper->_initNavigation] ERR: exception 'Exception' with message 'Class [EventNotificationTemplateConfigureAction] requires permissions [Array
(
--
]' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:
#0 /opt/kaltura/app/ui_infra/InfraBootstrapper.php(113): KalturaLog::err('Class [EventNot...')
--
#6 {main}
2015-01-14 12:28:32 [861271409] [InfraBootstrapper->_initNavigation] ERR: exception 'Exception' with message 'Class [EventNotificationTemplateUpdateStatusAction] requires permissions [Array
(
--
]' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:
#0 /opt/kaltura/app/ui_infra/InfraBootstrapper.php(113): KalturaLog::err('Class [EventNot...')

I run without SSL so I changed the flag in my DB and no IS_SSL setted. Kaltlog give this

--
2015-01-14 12:34:31 [0.000356] [192.168.0.136] [2004920206] [PS2] [sfView->initialize] INFO: {sfView} initialize view for "kmc/kmc1"
2015-01-14 12:34:31 [0.000583] [192.168.0.136] [2004920206] [PS2] [sfPHPView->renderFile] INFO: {sfView} render "/opt/kaltura/app/alpha/apps/kaltura/modules/kmc/templates/kmc1Success.php"
2015-01-14 12:34:31 [0.001222] [192.168.0.136] [2004920206] [PS2] [sfPHPView->decorate] INFO: {sfView} decorate content with "/opt/kaltura/app/alpha/apps/kaltura/templates/kmc1layout.php"
2015-01-14 12:34:31 [0.000257] [192.168.0.136] [2004920206] [PS2] [sfPHPView->renderFile] INFO: {sfView} render "/opt/kaltura/app/alpha/apps/kaltura/templates/kmc1layout.php"
2015-01-14 12:34:31 [0.000838] [192.168.0.136] [2004920206] [PS2] [sfRenderingFilter->execute] INFO: {sfFilter} render to client

Nothing else, and page is blank. I really spent a long time trying make Kaltura CE work but I'm running out of ideas.

**Comment by Atheryl** [comment]
Update,

[2015-01-14 11:06:06]failed to connect [1] [0.0018320083618164] mysql:host=127.0.0.1;port=3306;dbname=kaltura_sphinx_log;
PHP Fatal error:  Uncaught exception 'PropelException' with message 'Unable to open PDO connection dsn[mysql:host=127.0.0.1;port=3306;dbname=kaltura_sphinx_log;] user[kaltura] password[xxxxxxx] [wrapped: SQLSTATE[28000] [1045] Access denied for user 'kaltura'@'localhost' (using password: YES)]' in /opt/kaltura/app/vendor/propel/Propel.php:649
Stack trace:
#0 /opt/kaltura/app/vendor/propel/Propel.php(532): Propel::initConnection(Array, 'sphinx_log')
--
2015-01-14 14:05:43 [0.000330] [192.168.0.136] [1554751782] [PS2] [sfView->initialize] INFO: {sfView} initialize view for "kmc/kmc1"
2015-01-14 14:05:43 [0.000531] [192.168.0.136] [1554751782] [PS2] [sfPHPView->renderFile] INFO: {sfView} render "/opt/kaltura/app/alpha/apps/kaltura/modules/kmc/templates/kmc1Success.php"
2015-01-14 14:05:43 [0.000945] [192.168.0.136] [1554751782] [PS2] [sfPHPView->decorate] INFO: {sfView} decorate content with "/opt/kaltura/app/alpha/apps/kaltura/templates/kmc1layout.php"
2015-01-14 14:05:43 [0.000205] [192.168.0.136] [1554751782] [PS2] [sfPHPView->renderFile] INFO: {sfView} render "/opt/kaltura/app/alpha/apps/kaltura/templates/kmc1layout.php"
2015-01-14 14:05:43 [0.000848] [192.168.0.136] [1554751782] [PS2] [sfRenderingFilter->execute] INFO: {sfFilter} render to client
--
2015-01-14 11:07:08 [87179369] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message 'ERROR - Permission name [] for partner [0] not found in database - skipping!' in /opt/kaltura/app/infra/log/KalturaLog.php:64
Stack trace:
#0 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(280): KalturaLog::alert('ERROR - Permiss...')
--
==> /opt/kaltura/log/batch/validatelivemediaservers-0-2015-01-14.err.log <==
PHP Fatal error:  Uncaught exception 'KalturaException' with message 'Internal server error occurred' in /opt/kaltura/app/batch/client/KalturaClientBase.php:734
Stack trace:
#0 /opt/kaltura/app/batch/client/KalturaClient.php(4098): KalturaClientBase->throwExceptionIfError(Array)


I can connect perfectly with the username and password provided in the logs if I try and it seems not occurring anymore anyway since 11 am.

**Comment by Atheryl** [comment]
https://github.com/kaltura/platform-install-packages/issues/261

Seems it's just needed to create a publisher ... and it works ... It costed me over a day. I believe a message on the KMC page would help.

**Comment by jessp01** [comment]
Hi,

Thank you for the feedback.
We intend to add a message about this in the future, you are correct in saying it is confusing.
