### ISSUE TITLE
 Installation issues: Kaltura 10.4.0-1 on Redhat6.6 “Invalid object id[0]” and other issues.

### ISSUE THREAD

**Issue by kiranp** [kaltura/platform-install-packages#348]
I am trying to install latest Kaltura (10.4.0-1) on "Red Hat Enterprise Linux Server release 6.6 (Santiago)".  Have been running into several issues with the installation, especially with getting Admin Console to work. (Errors such as "Publisher: <hostname> Invalid user id" when I login to Admin Console, a random "Invalid_KS" etc). I got around all those issues and some other issues with installer, after fair amount of troubleshooting. Now, I am running into this error when I try to launch Admin Console:

{code}
    2015-02-16 16:19:37 [0.000988] [50.184.217.225] [219539087] [API] [KalturaFrontController->getExceptionObject] ERR: exception 'KalturaAPIException' with message 'Invalid object id [0]' in /opt/kaltura/app/api_v3/services/UserRoleService.php:91
{code}

Ran kaltura-sanity.sh
Output:
{code}
    [Space on /] [PASSED, RC: 0] - [.003070132]
    [Space on /opt/kaltura/web] [PASSED, RC: 0] - [.003066093]
    [Check httpd daemon status] [PASSED, RC: 0] - [.025768718]
    Napping 1 seconds to allow the daemon httpd to finish its init after monit restarted it..
    Napping 1 seconds to allow the daemon httpd to finish its init after monit restarted it..
    Napping 1 seconds to allow the daemon httpd to finish its init after monit restarted it..
    Napping 1 seconds to allow the daemon httpd to finish its init after monit restarted it..
    Napping 1 seconds to allow the daemon httpd to finish its init after monit restarted it..
    Napping 1 seconds to allow the daemon httpd to finish its init after monit restarted it..
    Napping 1 seconds to allow the daemon httpd to finish its init after monit restarted it..
    Napping 1 seconds to allow the daemon httpd to finish its init after monit restarted it..
    Napping 1 seconds to allow the daemon httpd to finish its init after monit restarted it..
    Napping 1 seconds to allow the daemon httpd to finish its init after monit restarted it..
    [Check httpd daemon is started by Monit] [PASSED, RC: 0] - [11.321704310]
    [check daemon httpd init status] [PASSED, RC: 0] - [.005055916]
    [Check kaltura-sphinx daemon status] [PASSED, RC: 0] - [.036161250]
    Napping 1 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
    Napping 1 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
    Napping 1 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
    Napping 1 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
    Napping 1 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
    Napping 1 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
    Napping 1 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
    [Check kaltura-sphinx daemon is started by Monit] [PASSED, RC: 0] - [7.779686113]
    [check daemon kaltura-sphinx init status] [PASSED, RC: 0] - [.004314777]
    [Check kaltura-batch daemon status] [PASSED, RC: 0] - [.025591255]
    Napping 1 seconds to allow the daemon kaltura-batch to finish its init after monit restarted it..
    Napping 1 seconds to allow the daemon kaltura-batch to finish its init after monit restarted it..
    Napping 1 seconds to allow the daemon kaltura-batch to finish its init after monit restarted it..
    Napping 1 seconds to allow the daemon kaltura-batch to finish its init after monit restarted it..
    Napping 1 seconds to allow the daemon kaltura-batch to finish its init after monit restarted it..
    Napping 1 seconds to allow the daemon kaltura-batch to finish its init after monit restarted it..
    Napping 1 seconds to allow the daemon kaltura-batch to finish its init after monit restarted it..
    Napping 1 seconds to allow the daemon kaltura-batch to finish its init after monit restarted it..
    [Check kaltura-batch daemon is started by Monit] [PASSED, RC: 0] - [8.215515169]
    [check daemon kaltura-batch init status] [PASSED, RC: 0] - [.003919044]
    [Check kaltura-monit daemon status] [PASSED, RC: 0] - [.017541722]
    [check daemon kaltura-monit init status] [PASSED, RC: 0] - [.003928550]
    [Check memcached daemon status] [PASSED, RC: 0] - [.017370444]
    Napping 1 seconds to allow the daemon memcached to finish its init after monit restarted it..
    Napping 1 seconds to allow the daemon memcached to finish its init after monit restarted it..
    Napping 1 seconds to allow the daemon memcached to finish its init after monit restarted it..
    Napping 1 seconds to allow the daemon memcached to finish its init after monit restarted it..
    Napping 1 seconds to allow the daemon memcached to finish its init after monit restarted it..
    Napping 1 seconds to allow the daemon memcached to finish its init after monit restarted it..
    Napping 1 seconds to allow the daemon memcached to finish its init after monit restarted it..
    [Check memcached daemon is started by Monit] [PASSED, RC: 0] - [7.262274607]
    [check daemon memcached init status] [PASSED, RC: 0] - [.004111495]
    [kaltura-html5lib ver in KMC config.ini] [PASSED, RC: 0] - [.067955556]
    [kaltura-kdp3 ver in KDP3 config.ini] [PASSED, RC: 0] - [.036589998]
    [kaltura-kmc ver in KMC config.ini] [PASSED, RC: 0] - [.041154677]
    [Get KMC SWFs] [PASSED, RC: 0] - [.141444536]
    [check_testme_page] [PASSED, RC: 0] - [10.098046282]
    [check_kmc_index_page] [PASSED, RC: 0] - [.017431906]
    [check_admin_console_index_page] [PASSED, RC: 0] - [10.148367195]
    [check_studio_index_page] [FAILED, RC: 1] - [5.582479320]
    [Create Partner] [FAILED, RC: 255] - [6.056216273]
    Partner creation failed. I will skip all tests that require it.
    [Red5 file upload] [PASSED, RC: 0] - [3.023562415]
    
    
    Thank you for running Kaltura! To keep Kaltura viable, stable and well tested, please join the community and help by contributing sanity tests that verify overall platform stability: http://bit.ly/kaltura-ci , and by contributing to the project roadmap by solving simple tasks and challenges: http://bit.ly/kaltura-tasks.
{code}

Kaltlog shows these errors:
{code}
    2015-02-16 17:28:47 [2117575988] [InfraBootstrapper->_initNavigation] DEBUG: Loading plugin[eventNotification]
    2015-02-16 17:28:47 [2117575988] [InfraBootstrapper->_initNavigation] ERR: exception 'Exception' with message 'Class [KalturaInternalToolsPluginSystemHelperAction] requires permissions [Array
    (
    --
    ]' in /opt/kaltura/app/infra/log/KalturaLog.php:82
    Stack trace:
    #0 /opt/kaltura/app/ui_infra/InfraBootstrapper.php(113): KalturaLog::err('Class [KalturaI...')
    --
    #6 {main}
    2015-02-16 17:28:47 [2117575988] [InfraBootstrapper->_initNavigation] ERR: exception 'Exception' with message 'Class [VirusScanListAction] requires permissions [Array
    (
    --
    ]' in /opt/kaltura/app/infra/log/KalturaLog.php:82
    Stack trace:
    #0 /opt/kaltura/app/ui_infra/InfraBootstrapper.php(113): KalturaLog::err('Class [VirusSca...')
    --
    #6 {main}
    2015-02-16 17:28:47 [2117575988] [InfraBootstrapper->_initNavigation] ERR: exception 'Exception' with message 'Class [VirusScanConfigureAction] requires permissions [Array
    (
    --
    ]' in /opt/kaltura/app/infra/log/KalturaLog.php:82
    Stack trace:
    #0 /opt/kaltura/app/ui_infra/InfraBootstrapper.php(113): KalturaLog::err('Class [VirusSca...')
    --
    #6 {main}
    2015-02-16 17:28:47 [2117575988] [InfraBootstrapper->_initNavigation] ERR: exception 'Exception' with message 'Class [VirusScanSetStatusAction] requires permissions [Array
    (
    --
    ]' in /opt/kaltura/app/infra/log/KalturaLog.php:82
    Stack trace:
    #0 /opt/kaltura/app/ui_infra/InfraBootstrapper.php(113): KalturaLog::err('Class [VirusSca...')
    --
    #6 {main}
    2015-02-16 17:28:47 [2117575988] [InfraBootstrapper->_initNavigation] ERR: exception 'Exception' with message 'Class [DistributionProfileListAction] requires permissions [Array
    (
    --
    ]' in /opt/kaltura/app/infra/log/KalturaLog.php:82
    Stack trace:
    #0 /opt/kaltura/app/ui_infra/InfraBootstrapper.php(113): KalturaLog::err('Class [Distribu...')
    --
    #6 {main}
    2015-02-16 17:28:47 [2117575988] [InfraBootstrapper->_initNavigation] ERR: exception 'Exception' with message 'Class [DistributionProfileConfigureAction] requires permissions [Array
    (
    --
    ]' in /opt/kaltura/app/infra/log/KalturaLog.php:82
    Stack trace:
    #0 /opt/kaltura/app/ui_infra/InfraBootstrapper.php(113): KalturaLog::err('Class [Distribu...')
    --
    #6 {main}
    2015-02-16 17:28:47 [2117575988] [InfraBootstrapper->_initNavigation] ERR: exception 'Exception' with message 'Class [DistributionProfileUpdateStatusAction] requires permissions [Array
    (
    --
    ]' in /opt/kaltura/app/infra/log/KalturaLog.php:82
    Stack trace:
    #0 /opt/kaltura/app/ui_infra/InfraBootstrapper.php(113): KalturaLog::err('Class [Distribu...')
    --
    #6 {main}
    2015-02-16 17:28:47 [2117575988] [InfraBootstrapper->_initNavigation] ERR: exception 'Exception' with message 'Class [GenericDistributionProvidersListAction] requires permissions [Array
    (
    --
    ]' in /opt/kaltura/app/infra/log/KalturaLog.php:82
    Stack trace:
    #0 /opt/kaltura/app/ui_infra/InfraBootstrapper.php(113): KalturaLog::err('Class [GenericD...')
    --
    #6 {main}
    2015-02-16 17:28:47 [2117575988] [InfraBootstrapper->_initNavigation] ERR: exception 'Exception' with message 'Class [GenericDistributionProviderConfigureAction] requires permissions [Array
    (
    --
    ]' in /opt/kaltura/app/infra/log/KalturaLog.php:82
    Stack trace:
    #0 /opt/kaltura/app/ui_infra/InfraBootstrapper.php(113): KalturaLog::err('Class [GenericD...')
    --
    #6 {main}
    2015-02-16 17:28:47 [2117575988] [InfraBootstrapper->_initNavigation] ERR: exception 'Exception' with message 'Class [GenericDistributionProviderDeleteAction] requires permissions [Array
    (
    --
    ]' in /opt/kaltura/app/infra/log/KalturaLog.php:82
    Stack trace:
    #0 /opt/kaltura/app/ui_infra/InfraBootstrapper.php(113): KalturaLog::err('Class [GenericD...')
    --
    #6 {main}
    2015-02-16 17:28:47 [2117575988] [InfraBootstrapper->_initNavigation] ERR: exception 'Exception' with message 'Class [XsltTesterAction] requires permissions [Array
    (
    --
    ]' in /opt/kaltura/app/infra/log/KalturaLog.php:82
    Stack trace:
    #0 /opt/kaltura/app/ui_infra/InfraBootstrapper.php(113): KalturaLog::err('Class [XsltTest...')
    --
    #6 {main}
    2015-02-16 17:28:47 [2117575988] [InfraBootstrapper->_initNavigation] ERR: exception 'Exception' with message 'Class [XsltTesterApiAction] requires permissions [Array
    (
    --
    ]' in /opt/kaltura/app/infra/log/KalturaLog.php:82
    Stack trace:
    #0 /opt/kaltura/app/ui_infra/InfraBootstrapper.php(113): KalturaLog::err('Class [XsltTest...')
    --
    #6 {main}
    2015-02-16 17:28:47 [2117575988] [InfraBootstrapper->_initNavigation] ERR: exception 'Exception' with message 'Class [DropFolderListAction] requires permissions [Array
    (
    --
    ]' in /opt/kaltura/app/infra/log/KalturaLog.php:82
    Stack trace:
    #0 /opt/kaltura/app/ui_infra/InfraBootstrapper.php(113): KalturaLog::err('Class [DropFold...')
    --
    #6 {main}
    2015-02-16 17:28:47 [2117575988] [InfraBootstrapper->_initNavigation] ERR: exception 'Exception' with message 'Class [DropFolderConfigureAction] requires permissions [Array
    (
    --
    ]' in /opt/kaltura/app/infra/log/KalturaLog.php:82
    Stack trace:
    #0 /opt/kaltura/app/ui_infra/InfraBootstrapper.php(113): KalturaLog::err('Class [DropFold...')
    --
    #6 {main}
    2015-02-16 17:28:47 [2117575988] [InfraBootstrapper->_initNavigation] ERR: exception 'Exception' with message 'Class [DropFolderSetStatusAction] requires permissions [Array
    (
    --
    ]' in /opt/kaltura/app/infra/log/KalturaLog.php:82
    Stack trace:
    #0 /opt/kaltura/app/ui_infra/InfraBootstrapper.php(113): KalturaLog::err('Class [DropFold...')
    --
    #6 {main}
    2015-02-16 17:28:47 [2117575988] [InfraBootstrapper->_initNavigation] ERR: exception 'Exception' with message 'Class [EventNotificationTemplatesListAction] requires permissions [Array
    (
    --
    ]' in /opt/kaltura/app/infra/log/KalturaLog.php:82
    Stack trace:
    #0 /opt/kaltura/app/ui_infra/InfraBootstrapper.php(113): KalturaLog::err('Class [EventNot...')
    --
    #6 {main}
    2015-02-16 17:28:47 [2117575988] [InfraBootstrapper->_initNavigation] ERR: exception 'Exception' with message 'Class [EventNotificationTemplateConfigureAction] requires permissions [Array
    (
    --
    ]' in /opt/kaltura/app/infra/log/KalturaLog.php:82
    Stack trace:
    #0 /opt/kaltura/app/ui_infra/InfraBootstrapper.php(113): KalturaLog::err('Class [EventNot...')
    --
    #6 {main}
    2015-02-16 17:28:47 [2117575988] [InfraBootstrapper->_initNavigation] ERR: exception 'Exception' with message 'Class [EventNotificationTemplateUpdateStatusAction] requires permissions [Array
    (
    --
    ]' in /opt/kaltura/app/infra/log/KalturaLog.php:82
    Stack trace:
    #0 /opt/kaltura/app/ui_infra/InfraBootstrapper.php(113): KalturaLog::err('Class [EventNot...')
    --
    ==> /opt/kaltura/log/kaltura_apache_errors.log <==
    [Mon Feb 16 17:28:53 2015] [error] [client 10.136.99.186] File does not exist: /opt/kaltura/app/alpha/web/apps
{code}

Any suggestions on how to fix these errors?

**Comment by DBezemer** [comment]
@kiranp and updates on your install attempts?
If you're still running into these errors, please post the error messages that occurred before trying to access the application.

Typically these errors occur because curl cannot connect to your specified domain name, so make sure your hostname resolves correctly and there are no firewalls interfering.
