### ISSUE TITLE
using chef db_config step breaks

### ISSUE THREAD

**Issue by nukepuppy** [kaltura/platform-install-packages#381]
during the db_config using chef (or manual)

the same step always fails

```
Queuing action [userRole.add]
Queuing action [user.add]
Executing multirequest
service url: [kalfrontend.whateverdomain.com]
curl: kalfrontend.whateverdomain.com/api_v3/index.php?service=multirequest&format=3&ignoreNull=1&clientTag=php5%3A15-04-16&apiVersion=3.2.0&1%3Aservice=userrole&1%3Aaction=add&1%3AuserRole%3AobjectType=KalturaUserRole&1%3AuserRole%3Aname=System+Administrator&1%3AuserRole%3AsystemName=System+Administrator&1%3AuserRole%3Adescription=System+Administrator&1%3AuserRole%3Astatus=1&1%3AuserRole%3ApermissionNames=%2A&1%3AuserRole%3Atags=admin_console&1%3Aks=YjFiZjIwYzYzOWI4YjdhNDlhNWM1Njg4ZDIyZjFiODA3MmJlNGFlN3wtMjstMjsxNDI5MjkxMTA2OzI7NTI0MTs7&2%3Aservice=user&2%3Aaction=add&2%3Auser%3AobjectType=KalturaUser&2%3Auser%3Aid=admins%40whateverdomain.com&2%3Auser%3AscreenName=admins%40whateverdomain.com&2%3Auser%3AfullName=Kaltura+Administrator&2%3Auser%3Aemail=admins%40whateverdomain.com&2%3Auser%3Astatus=1&2%3Auser%3Apassword=fakepass123&2%3Auser%3AisAdmin=1&2%3Auser%3AroleIds=%7B1%3Aresult%3Aid%7D&2%3Auser%3AallowedPartnerIds=%2A&2%3Aks=YjFiZjIwYzYzOWI4YjdhNDlhNWM1Njg4ZDIyZjFiODA3MmJlNGFlN3wtMjstMjsxNDI5MjkxMTA2OzI7NTI0MTs7&kalsig=a2a11844baf54231d0626b6e77290648
server: [kalfrontend.whateverdomain.com], session: [1774547409]
result (serialized): a:2:{i:0;a:4:{s:4:"code";s:10:"INVALID_KS";s:7:"message";s:125:"Invalid KS "YjFiZjIwYzYzOWI4YjdhNDlhNWM1Njg4ZDIyZjFiODA3MmJlNGFlN3wtMjstMjsxNDI5MjkxMTA2OzI7NTI0MTs7", Error "-1,INVALID_STR"";s:10:"objectType";s:19:"KalturaAPIException";s:4:"args";a:3:{s:4:"KSID";s:88:"YjFiZjIwYzYzOWI4YjdhNDlhNWM1Njg4ZDIyZjFiODA3MmJlNGFlN3wtMjstMjsxNDI5MjkxMTA2OzI7NTI0MTs7";s:8:"ERR_CODE";i:-1;s:8:"ERR_DESC";s:11:"INVALID_STR";}}i:1;a:4:{s:4:"code";s:10:"INVALID_KS";s:7:"message";s:125:"Invalid KS "YjFiZjIwYzYzOWI4YjdhNDlhNWM1Njg4ZDIyZjFiODA3MmJlNGFlN3wtMjstMjsxNDI5MjkxMTA2OzI7NTI0MTs7", Error "-1,INVALID_STR"";s:10:"objectType";s:19:"KalturaAPIException";s:4:"args";a:3:{s:4:"KSID";s:88:"YjFiZjIwYzYzOWI4YjdhNDlhNWM1Njg4ZDIyZjFiODA3MmJlNGFlN3wtMjstMjsxNDI5MjkxMTA2OzI7NTI0MTs7";s:8:"ERR_CODE";i:-1;s:8:"ERR_DESC";s:11:"INVALID_STR";}}}
result (object dump): Array
(
    [0] => Array
        (
            [code] => INVALID_KS
            [message] => Invalid KS "YjFiZjIwYzYzOWI4YjdhNDlhNWM1Njg4ZDIyZjFiODA3MmJlNGFlN3wtMjstMjsxNDI5MjkxMTA2OzI7NTI0MTs7", Error "-1,INVALID_STR"
            [objectType] => KalturaAPIException
            [args] => Array
                (
                    [KSID] => YjFiZjIwYzYzOWI4YjdhNDlhNWM1Njg4ZDIyZjFiODA3MmJlNGFlN3wtMjstMjsxNDI5MjkxMTA2OzI7NTI0MTs7
                    [ERR_CODE] => -1
                    [ERR_DESC] => INVALID_STR
                )

        )
```

any suggestions?

i try it on browser the same call and same error keeps coming up

The setup is
2kaltura front ends (load balanced)
2 sphinx (1 running the db config)
2 batch
1 dwh
1vod

**Comment by nukepuppy** [comment]
the order is based off the 
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.9.0/doc/rpm-chef-cluster-deployment.md

front ends done via chef
sphinx would be done via chef (failing on dbconfig)
batch not done yet
dwh not done yet
vod not done yet

**Comment by jessp01** [comment]
Hello,

Which Kaltura version are you using?
Also, are you working behind a load balancer? If so, you must disable all nodes but one while deploying the DB. The re-enable them later.

**Comment by nukepuppy** [comment]
looks like kaltura 10.8.0.. well whatever it installed when running the chef recipes as of last week.

I am running just the front end servers behind a load balancer
I did what you suggested and left just 1 front end node up.. and that seemed to have at least made it past the state it was before.

I essentially ran this manually from the SPHINX server which is a dedicated sphinx node ...
```
/opt/kaltura/bin/kaltura-db-config.sh MY.DB.SERVER.COM root fakepasswordhere 3306
```
when it finished it didn't exit 0.. it exited "11"

```
Checking MySQL version..
Ver 5.6.22-log found compatible

The kaltura DB seems to already be installed.

if you meant to perform an upgrade? run with:
# /opt/kaltura/bin/kaltura-db-config.sh kmdbaws1.bbcollab.com root bogus123 3306 upgrade

Otherwise, do you wish to remove the existing DB [n/Y]?

Y
This will drop the following DBs:
kaltura kaltura_sphinx_log kalturadw kalturadw_ds kalturadw_bisources kalturalog
and remove users:
kaltura etl
on kmdbaws1.bbcollab.com

NOTE: this is not reversible.
It is recommended you also back up the current data using mysqldump before continuing.
You can use /opt/kaltura/bin/kaltura-export-db.sh to export the data.

Are you absolutely certain you want this? [n/Y]

Y
root DB passwd:
Removing kaltura
Removing kaltura_sphinx_log
Removing kalturadw
Removing kalturadw_ds
Removing kalturadw_bisources
Removing kalturalog
CREATE USER kaltura;
CREATE USER etl;
CREATE DATABASE kaltura;
CREATE DATABASE kaltura_sphinx_log;
CREATE DATABASE kalturadw;
CREATE DATABASE kalturadw_ds;
CREATE DATABASE kalturadw_bisources;
CREATE DATABASE kalturalog;
Checking connectivity to needed daemons...
Connectivity test passed:)
Cleaning cache..
Populating DB with data.. please wait..
Output for /opt/kaltura/app/deployment/base/scripts/installPlugins.php being logged into /opt/kaltura/log/installPlugins.log
Output for /opt/kaltura/app/deployment/base/scripts/insertDefaults.php being logged into /opt/kaltura/log/insertDefaults.log
Output for /opt/kaltura/app/deployment/base/scripts/insertPermissions.php being logged into /opt/kaltura/log/insertPermissions.log
Output for /opt/kaltura/app/deployment/base/scripts/insertContent.php being logged into /opt/kaltura/log/insertContent.log
Generating UI confs..



		Archving logs to /opt/kaltura/log/log_20_04_15_13_32.tar.gz...
# $?
-bash: 11: command not found
```


however despite it exiting 11 i can login to the front end as an admin now... 


I see some new errors which makes me wonder? is the SPHINX servers supposed to have the shared storage mounted for /opt/kaltura/web?
from: deploy_v2.log on sphinx server
```
HP Fatal error:  Uncaught exception 'Zend_Config_Exception' with message 'parse_ini_file(/opt/kaltura/web/flash/kmc/v5.38.11/config.ini): failed to open stream: No such file or directory' in /opt/kaltura/app/vendor/ZendFramework/library/Zend/Config/Ini.php:184
```

other similar errors from /opt/kaltura/log/kaltura_scripts.log  on the sphinx server
```
[647254659] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message 'ERROR - Permission name [BATCH_BASE] for partner [0] not found in database - skipping!' in /opt/kaltura/app/infra/log/KalturaLog.php:64
Stack trace:
#0 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(280): KalturaLog::alert('ERROR - Permiss...')
#1 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(197): addItemToPermissions(Object(kApiActionPermissionItem), Array, '0')
#2 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(40): addActionPermissionItem(Object(Zend_Config))
#3 {main}
```

**Comment by nukepuppy** [comment]
I'm going on the assumption based on this doc: https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.9.0/doc/rpm-chef-cluster-deployment.md

that the sphinx server does NOT need to mount /opt/kaltura/web

```
# knife node run_list add mynfs kaltura::nfs-server
# knife node run_list add mynfs nfs::server
# knife node run_list add my-mysql-machine mysql::server 
# knife node run_list add my-batch-machine nfs 
# knife node run_list add my-batch-machine kaltura::batch 
# knife node run_list add my-sphinx-machine kaltura::sphinx
# knife node run_list add my-sphinx-machine kaltura::db_config
# knife node run_list add my-front-machine nfs 
# knife node run_list add my-front-machine kaltura::front 
# knife node run_list add my-dwh-machine nfs
# knife node run_list add my-dwh-machine kaltura::dwh 
# knife node run_list add my-vod-machine kaltura::vod-packager 
```

**Comment by jessp01** [comment]
Hello,

Sphinx - no need for the NFS to be mounted but should not do harm either.

Please open /opt/kaltura/log/insertContent.log and see what has failed. No 
point in using the system until that passes correctly.

As for which version, you can just run rpm -q kaltura-base to get it.

Thanks,

May the source be with you,

Jess Portnoy

Join us for the Kaltura Connect Virtual Summits 2015 - Register now!
connect.kaltura.com

**Comment by nukepuppy** [comment]
here is the version
# rpm -q kaltura-base
kaltura-base-10.8.0-14.noarch

**Comment by nukepuppy** [comment]
ok looks like we also had a password complexity issue?  i don't know if this is something automation should care about though :(  so that wasted some time

i was able to set a more complex password and get the UI confs to finish in the db_config to finish properly

```
Removing kaltura
Removing kaltura_sphinx_log
Removing kalturadw
Removing kalturadw_ds
Removing kalturadw_bisources
Removing kalturalog
CREATE USER kaltura;
CREATE USER etl;
CREATE DATABASE kaltura;
CREATE DATABASE kaltura_sphinx_log;
CREATE DATABASE kalturadw;
CREATE DATABASE kalturadw_ds;
CREATE DATABASE kalturadw_bisources;
CREATE DATABASE kalturalog;
Checking connectivity to needed daemons...
Connectivity test passed:)
Cleaning cache..
Populating DB with data.. please wait..
Output for /opt/kaltura/app/deployment/base/scripts/installPlugins.php being logged into /opt/kaltura/log/installPlugins.log
Output for /opt/kaltura/app/deployment/base/scripts/insertDefaults.php being logged into /opt/kaltura/log/insertDefaults.log
Output for /opt/kaltura/app/deployment/base/scripts/insertPermissions.php being logged into /opt/kaltura/log/insertPermissions.log
Output for /opt/kaltura/app/deployment/base/scripts/insertContent.php being logged into /opt/kaltura/log/insertContent.log
Generating UI confs..
myserver# $?
-bash: 0: command not found
```
