### ISSUE TITLE
Script Install Ubuntu 14.04 Debian 8

### ISSUE THREAD

**Issue by jniltinho** [kaltura/platform-install-packages#400]
Error install script:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.11.0/doc/install-kaltura-deb-based.md

Not run Ubuntu 14.04 64Bits
Not run Debian 8 64Bits

**Comment by jessp01** [comment]
Hello,

What exactly is the output?

**Comment by jniltinho** [comment]
Screencast install Kaltura Ubuntu 14.04 64Bits

http://youtu.be/5kO4wPwlgtg

**Comment by jniltinho** [comment]
Hello
Please send demo for download VM (Virtualbox, Vmware, XenServer .xva)  Ubuntu 14.04 64Bits
Kaltura is very complex to install

**Comment by jessp01** [comment]
Not getting anything from that link. Says 'video is being processed'.
Please just paste the output here.

**Comment by jniltinho** [comment]
Video OK,

Log -> log_22_05_15_10_53.tar.gz
https://drive.google.com/file/d/0B_QvF91p_eFWREs4bEp1eF9wUUE/view?usp=sharing

**Comment by jessp01** [comment]
I am not seeing it. Please just paste the output here, no need for a video.
Also, what is in the error logs under: /opt/kaltura/log
?

**Comment by jniltinho** [comment]
cat kaltura_scripts.log
2015-05-22 10:52:05 [876684340] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message 'ERROR - Permission name [BATCH_BASE] for partner [0] not found in database - skipping!' in /opt/kaltura/app/infra/log/KalturaLog.php:64
Stack trace:
#0 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(280): KalturaLog::alert('ERROR - Permiss...')
#1 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(197): addItemToPermissions(Object(kApiActionPermissionItem), Array, '0')
#2 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(40): addActionPermissionItem(Object(Zend_Config))
#3 {main}
2015-05-22 10:52:32 [1822663586] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message 'ERROR - Permission name [BATCH_BASE] for partner [0] not found in database - skipping!' in /opt/kaltura/app/infra/log/KalturaLog.php:64
Stack trace:
#0 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(280): KalturaLog::alert('ERROR - Permiss...')
#1 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(197): addItemToPermissions(Object(kApiActionPermissionItem), Array, '0')
#2 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(40): addActionPermissionItem(Object(Zend_Config))
#3 {main}
2015-05-22 10:53:10 [326866695] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message 'ERROR - Permission name [MEDIA_SERVER_BASE] for partner [-1] not found in database - skipping!' in /opt/kaltura/app/infra/log/KalturaLog.php:64
Stack trace:
#0 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(280): KalturaLog::alert('ERROR - Permiss...')
#1 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(197): addItemToPermissions(Object(kApiActionPermissionItem), Array, '-1')
#2 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(40): addActionPermissionItem(Object(Zend_Config))
#3 {main}
2015-05-22 10:53:21 [1373849952] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message 'ERROR - Permission name [] for partner [0] not found in database - skipping!' in /opt/kaltura/app/infra/log/KalturaLog.php:64
Stack trace:
#0 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(280): KalturaLog::alert('ERROR - Permiss...')
#1 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(197): addItemToPermissions(Object(kApiActionPermissionItem), Array, '0')
#2 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(40): addActionPermissionItem(Object(Zend_Config))
#3 {main}

**Comment by jniltinho** [comment]
cat kaltura_scripts.log
2015-05-22 10:52:05 [876684340] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message 'ERROR - Permission name [BATCH_BASE] for partner [0] not found in database - skipping!' in /opt/kaltura/app/infra/log/KalturaLog.php:64
Stack trace:
#0 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(280): KalturaLog::alert('ERROR - Permiss...')
#1 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(197): addItemToPermissions(Object(kApiActionPermissionItem), Array, '0')
#2 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(40): addActionPermissionItem(Object(Zend_Config))
#3 {main}
2015-05-22 10:52:32 [1822663586] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message 'ERROR - Permission name [BATCH_BASE] for partner [0] not found in database - skipping!' in /opt/kaltura/app/infra/log/KalturaLog.php:64
Stack trace:
#0 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(280): KalturaLog::alert('ERROR - Permiss...')
#1 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(197): addItemToPermissions(Object(kApiActionPermissionItem), Array, '0')
#2 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(40): addActionPermissionItem(Object(Zend_Config))
#3 {main}
2015-05-22 10:53:10 [326866695] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message 'ERROR - Permission name [MEDIA_SERVER_BASE] for partner [-1] not found in database - skipping!' in /opt/kaltura/app/infra/log/KalturaLog.php:64
Stack trace:
#0 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(280): KalturaLog::alert('ERROR - Permiss...')
#1 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(197): addItemToPermissions(Object(kApiActionPermissionItem), Array, '-1')
#2 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(40): addActionPermissionItem(Object(Zend_Config))
#3 {main}
2015-05-22 10:53:21 [1373849952] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message 'ERROR - Permission name [] for partner [0] not found in database - skipping!' in /opt/kaltura/app/infra/log/KalturaLog.php:64
Stack trace:
#0 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(280): KalturaLog::alert('ERROR - Permiss...')
#1 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(197): addItemToPermissions(Object(kApiActionPermissionItem), Array, '0')
#2 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(40): addActionPermissionItem(Object(Zend_Config))
#3 {main}

**Comment by jessp01** [comment]
It seems your DB is broken.

I suggest you use kaltura-drop-db.sh to remove it and then: 
\# dpkg-reconfigure kaltura-db
\# dpkg-reconfigure kaltura-base
\# dpkg-reconfigure kaltura-front
\# dpkg-reconfigure kaltura-batch

If, after that, you still have issues, please post on forum.kaltura.org as this is not a general bug.

Thanks,

**Comment by jniltinho** [comment]
not fix, Download VM VirtualBox or Vmware ?
