### ISSUE TITLE
Issue after upgrade from 10.x to 11.8

### ISSUE THREAD

**Issue by talhagithub** [kaltura/platform-install-packages#525]
Hi Support,

I have been running Kaltura single server configuration for over a year on CentOS 6 without any issue. I just did an upgrade using the CentOS method on Github with the following commands:

```
yum clean all
yum update kaltura-release
yum clean all
yum update "*kaltura*"

/opt/kaltura/bin/kaltura-db-update.sh
/opt/kaltura/bin/kaltura-config-all.sh
```

I could reconnect to KMC console and see all my 4,000 videos, however I cannot add anymore videos. It stays on "converting" status and does not go beyond it.

Any support will be greatly appreciated.

Regards,
talhagithub

**Here is the output of sanity-check script:**

```
[root@video ~]# /opt/kaltura/bin/kaltura-sanity.sh
[Space on /] [PASSED, RC: 0] - [.047094952]
[Space on /opt/kaltura/web] [PASSED, RC: 0] - [.005354447]
[Check httpd daemon status] [PASSED, RC: 0] - [.062018900]
Napping 1 seconds to allow the daemon httpd to finish its init after monit restarted it..
..
Napping 9 seconds to allow the daemon httpd to finish its init after monit restarted it..
[Check httpd daemon is started by Monit] [PASSED, RC: 0] - [10.560028081]
[check daemon httpd init status] [PASSED, RC: 0] - [.006897954]
[Check kaltura-sphinx daemon status] [PASSED, RC: 0] - [.044179028]
Napping 1 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
..
Napping 40 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..
[Check kaltura-sphinx daemon is started by Monit] [PASSED, RC: 0] - [53.041259946]
[check daemon kaltura-sphinx init status] [PASSED, RC: 0] - [.006180834]
[Check kaltura-batch daemon status] [PASSED, RC: 0] - [.039756418]
Napping 1 seconds to allow the daemon kaltura-batch to finish its init after monit restarted it..
..
Napping 50 seconds to allow the daemon kaltura-batch to finish its init after monit restarted it..
[Check kaltura-batch daemon is started by Monit] [PASSED, RC: 0] - [52.044626537]
[check daemon kaltura-batch init status] [PASSED, RC: 0] - [.006264686]
[Check kaltura-monit daemon status] [PASSED, RC: 0] - [.031505410]
[check daemon kaltura-monit init status] [PASSED, RC: 0] - [.005774023]
[Check memcached daemon status] [PASSED, RC: 0] - [.030905404]
Action failed -- Other action already in progress -- please try again later
.. (repeated 14 times)
Action failed -- Other action already in progress -- please try again later
Napping 1 seconds to allow the daemon memcached to finish its init after monit restarted it..
..
Napping 48 seconds to allow the daemon memcached to finish its init after monit restarted it..
[Check memcached daemon is started by Monit] [PASSED, RC: 0] - [49.949050514]
[check daemon memcached init status] [PASSED, RC: 0] - [.015002510]
[kaltura-html5lib ver in KMC config.ini] [PASSED, RC: 0] - [.165607560]
[kaltura-kdp3 ver in KDP3 config.ini] [PASSED, RC: 0] - [.058892741]
[kaltura-kmc ver in KMC config.ini] [PASSED, RC: 0] - [.066439650]
[Get KMC SWFs] [PASSED, RC: 0] - [.294752724]
[check_testme_page] [PASSED, RC: 0] - [.281061732]
[check_kmc_index_page] [PASSED, RC: 0] - [.024751048]
[check_admin_console_index_page] [PASSED, RC: 0] - [.664158636]
[check_studio_index_page] [PASSED, RC: 0] - [.045678415]
[check_clipapp_index_page] [PASSED, RC: 0] - [.772457840]
[Create Partner] [PASSED, RC: 0] - [2.420351586]
[Local dropfolder creation] [PASSED, RC: 0] - [.530554741]
[Create flavor param] [PASSED, RC: 0] - [.515103671]
[Delete flavor param] [PASSED, RC: 0] - [.243490356]
[HTTP notification: 
No HTTP templates exist.
 Try running:
php /opt/kaltura/app/tests/standAloneClient/exec.php /opt/kaltura/app/tests/standAloneClient/httpNotificationsTemplate.xml /tmp/out.xml
Passing -2 as partner ID] [PASSED, RC: 0] - [.515103671]
[Mail notification: ID: 17, Subject: Your video is ready to be played!, Mail body: Hello world:)] [PASSED, RC: 0] - [.515103671]
[Upload content kaltura_logo_animated_blue.flv] [PASSED, RC: 0] - [1.063849847]
Napping 10 seconds to allow entry 0_nsynq5ev to digest.. 
..
Napping 10 seconds to allow entry 0_nsynq5ev to digest.. 
**[kaltura_logo_animated_blue.flv - 0_nsynq5ev status] [FAILED, RC: 1] - [-.627084002]**
Napping 30 seconds to allow mail to be sent out.. 
[Found an email sending entry for mb-pkbits.com@kaltura.com[PID is 105] in /var/log/maillog] [PASSED, RC: 0] - [30.051611804]
Testing analytics, be patient..

Please note: if you are running this test on a clustered ENV, it will fail but this does not mean there is an actual problem.
The tech information as to why is available here: 
https://github.com/kaltura/platform-install-packages/issues/106#issuecomment-42837404

**[DWH cycle] [FAILED, RC: 255] - [5.808655273]**
[Upload content kaltura_logo_animated_green.flv] [PASSED, RC: 0] - [1.306843268]
[Upload bulk using CSV] [PASSED, RC: 0] - [.911152927]
[Upload bulk using XML] [PASSED, RC: 0] - [.430563543]
[Create player] [PASSED, RC: 0] - [.319286250]
[Generate thumb] [PASSED, RC: 0] - [.474380226]
[Delete partner] [PASSED, RC: 0] - [.648923215]
[Red5 file upload] [SKIPPED as OflaDemo isn't configured]
see: https://github.com/kaltura/platform-install-packages/blob/master/doc/install-kaltura-redhat-based.md#configure-red5-server


Thank you for running Kaltura! To keep Kaltura viable, stable and well tested, please join the community and help by contributing sanity tests that verify overall platform stability: http://bit.ly/kaltura-ci , and by contributing to the project roadmap by solving simple tasks and challenges: http://bit.ly/kaltura-tasks.
```

**Comment by talhagithub** [comment]
**Also sharing other outputs**

```
[root@video ~]# rpm -qa "kaltura*"
kaltura-libmcrypt-2.5.7-5.x86_64
kaltura-libmemcached-1.0.16-2.x86_64
kaltura-kdp3wrapper-v37.0-1.noarch
kaltura-kdp3-v3.9.9-2.noarch
kaltura-release-11.8.0-1.noarch
kaltura-segmenter-1.0-2.x86_64
kaltura-html5-studio-v2.0.2-1.noarch
kaltura-front-11.8.0-1.noarch
kaltura-clipapp-1.3-2.noarch
kaltura-pentaho-4.2.1-2.x86_64
kaltura-libfaac-1.26-1.x86_64
kaltura-libass-0.9.11-2.x86_64
kaltura-sshpass-1.05-1.x86_64
kaltura-lame-3.99.5-3.x86_64
kaltura-libmcrypt-devel-2.5.7-5.x86_64
kaltura-librtmp-2.3-2.x86_64
kaltura-fdk-acc-0.1.3-1.x86_64
kaltura-kupload-1.0.0-1.noarch
kaltura-krecord-1.0.0-1.noarch
kaltura-kvpm-v1.0.6-1.noarch
kaltura-kcw-1.0.0-6.noarch
kaltura-widgets-1.0.0-8.noarch
kaltura-mencoder-3.4.6-9.x86_64
kaltura-nginx-1.8.0-12.x86_64
kaltura-ffmpeg-aux-2.1.3-1.x86_64
kaltura-base-11.8.0-12.noarch
kaltura-sphinx-2.2.1-17.x86_64
kaltura-batch-11.8.0-2.noarch
kaltura-kmc-v5.40.1-3.noarch
kaltura-red5-1.0.6-1.x86_64
kaltura-dwh-11.3.0-1.noarch
kaltura-a52dec-0.7.4-11.x86_64
kaltura-x264-0.140-2.20140104.x86_64
kaltura-libopencore-amr-0.1.2-2.x86_64
kaltura-flexwrapper-v1.2-1.noarch
kaltura-kclip-v1.1.2.1-2.noarch
kaltura-kdpwrapper-v11.0-1.noarch
kaltura-kdp-v2.7.0-1.noarch
kaltura-monit-5.13-1.x86_64
kaltura-ffmpeg-2.7.2-2.x86_64
kaltura-postinst-1.0.31-2.noarch
kaltura-html5lib-v2.40-1.noarch
kaltura-server-11.8.0-1.noarch
```

**The following is the log output during file upload and conversion:**

```
==> /opt/kaltura/log/kaltura_apache_errors.log <==
[Tue Feb 23 09:37:50 2016] [error] [client 94.23.51.20] File does not exist: /opt/kaltura/app/alpha/web/about, referer: http://video.com/
[Tue Feb 23 10:06:11 2016] [error] [client 94.23.51.20] File does not exist: /opt/kaltura/app/alpha/web/about, referer: http://video.com/
[Tue Feb 23 10:09:30 2016] [error] [client 94.23.51.20] File does not exist: /opt/kaltura/app/alpha/web/about, referer: http://video.com/
[Tue Feb 23 10:53:57 2016] [error] [client 45.72.2.160] File does not exist: /opt/kaltura/app/alpha/web/about, referer: http://video.com/

--
  thrown in /opt/kaltura/app/batch/client/KalturaClientBase.php on line 362
PHP Fatal error:  Uncaught exception 'KalturaException' with message 'Internal server error occurred' in /opt/kaltura/app/batch/client/KalturaClientBase.php:894
Stack trace:
#0 /opt/kaltura/app/batch/client/KalturaClient.php(4130): KalturaClientBase->throwExceptionIfError(Array)
--
2016-02-23 10:54:46 [0.000000] [467643255] [1] [BATCH] [KSchedulerConfig->load] NOTICE: loading configuration /opt/kaltura/app/configurations/batch at 1456217975
PHP Warning:  file_put_contents(/batch.pid): failed to open stream: Permission denied in /opt/kaltura/app/batch/scheduler/KGenericScheduler.class.php on line 97
2016-02-23 10:54:46 [0.078100] [467643255] [2] [BATCH] [KGenericScheduler->loadConfig] INFO: 2.0.2
--
    [line:protected] => 43
    [trace:Exception:private] => Array
        (
--
==> /opt/kaltura/log/kaltura_prod.log <==
2016-02-23 10:55:43 [0.000305] [82.147.207.174] [893329595] [54] [PS2] [KExternalErrors::dieError] ERR: exception 'Exception' with message 'exiting on error 6 - requested flavor was not found' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/alpha/apps/kaltura/lib/KExternalErrors.class.php(128): KalturaLog::err('exiting on erro...')
--
2016-02-23 10:55:57 [0.000000] [552199112] [1] [BATCH] [KSchedulerConfig->load] NOTICE: loading configuration /opt/kaltura/app/configurations/batch at 1456217975
PHP Warning:  file_put_contents(/batch.pid): failed to open stream: Permission denied in /opt/kaltura/app/batch/scheduler/KGenericScheduler.class.php on line 97
2016-02-23 10:55:57 [0.077375] [552199112] [2] [BATCH] [KGenericScheduler->loadConfig] INFO: 2.0.2
--
            [tmp_name] => /opt/kaltura/web/tmp/phpdw38Vv
            [error] => 0
            [size] => 321830
--
            [tmp_name] => /opt/kaltura/web/tmp/phpdw38Vv
            [error] => 0
            [size] => 321830
--
    [line:protected] => 43
    [trace:Exception:private] => Array
        (
--
    [line:protected] => 43
    [trace:Exception:private] => Array
        (
--
]
2016-02-23 10:56:51 [0.000704] [95.211.213.168] [399080053] [265] [API] [kBatchManager::createFlavorAsset] ERR: exception 'Exception' with message 'Flavor [7] is none-comply' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/alpha/apps/kaltura/lib/batch2/kBatchManager.php(88): KalturaLog::err('Flavor [7] is n...')
--
2016-02-23 10:56:51 [0.000711] [95.211.213.168] [399080053] [276] [API] [KalturaStatement->execute] DEBUG: Sql took - 0.0004878044128418 seconds
2016-02-23 10:56:51 [0.000595] [95.211.213.168] [399080053] [277] [API] [kBatchManager::createFlavorAsset] ERR: exception 'Exception' with message 'Flavor [6] is none-comply' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/alpha/apps/kaltura/lib/batch2/kBatchManager.php(88): KalturaLog::err('Flavor [6] is n...')
--
2016-02-23 10:56:51 [0.000410] [95.211.213.168] [1077642613] [15] [API] [KalturaStatement->execute] DEBUG: Sql took - 0.00023102760314941 seconds
2016-02-23 10:56:51 [0.000398] [95.211.213.168] [399080053] [289] [API] [kBatchManager::createFlavorAsset] ERR: exception 'Exception' with message 'Flavor [3] is none-comply' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/alpha/apps/kaltura/lib/batch2/kBatchManager.php(88): KalturaLog::err('Flavor [3] is n...')
--
2016-02-23 10:57:07 [0.000000] [1691949731] [1] [BATCH] [KSchedulerConfig->load] NOTICE: loading configuration /opt/kaltura/app/configurations/batch at 1456217975
PHP Warning:  file_put_contents(/batch.pid): failed to open stream: Permission denied in /opt/kaltura/app/batch/scheduler/KGenericScheduler.class.php on line 97
2016-02-23 10:57:07 [0.078718] [1691949731] [2] [BATCH] [KGenericScheduler->loadConfig] INFO: 2.0.2
--
==> /opt/kaltura/log/kaltura_prod.log <==
2016-02-23 10:58:04 [0.000792] [82.147.207.174] [2034865351] [39] [PS2] [KExternalErrors::dieError] ERR: exception 'Exception' with message 'exiting on error 11 - processing capture thumbnail' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/alpha/apps/kaltura/lib/KExternalErrors.class.php(128): KalturaLog::err('exiting on erro...')
--
    [line:protected] => 43
    [trace:Exception:private] => Array
        (
--
    [line:protected] => 43
    [trace:Exception:private] => Array
        (
--
    [line:protected] => 43
    [trace:Exception:private] => Array
        (
--
==> /opt/kaltura/log/kaltura_batch.log <==
PHP Warning:  file_put_contents(/batch.pid): failed to open stream: Permission denied in /opt/kaltura/app/batch/scheduler/KGenericScheduler.class.php on line 97
2016-02-23 10:58:17 [0.121869] [999406820] [2] [BATCH] [KGenericScheduler->loadConfig] INFO: 2.0.2


```

**Comment by ifproject** [comment]
This is excactly what happened to me, described here  https://github.com/kaltura/platform-install-packages/issues/523 , still no solution for me.

Did you check Monitoring to see if batch is running? In my case batch is not running and cannot be restarted, so no new videos can be converted.

**Comment by talhagithub** [comment]
Hi ifproject,

Thanks for sharing, I checked your issue and it seems different as mine seems related to permissions for writing during conversion. I re-ran the install scripts but they didn't resolve the permission issue.

Looking desperately for help!

Thanks everyone in advance.
talhagithub

**Comment by peterrei** [comment]
I have the same problem, I can confirm the problem during batch conversion, and also, that sanity test don't report any issue about batch.
My kaltlog output is the follow:
https://dl.dropboxusercontent.com/u/72357116/kaltlog.txt

Maybe could be useful highlight that the batch.pid don't exists after the upgrade to 11.8.0 or installing 11.7.0 from scratch (it seems confirmed reading another open issues in 11.8.0 

I open a thread in official forum about it: https://forum.kaltura.org/t/file-conversion-does-not-work-in-11-8-0-kaltura/4495/4

My suggestion is rollback to 11.7.0 that works fine talking about the batch conversion.


AML

**Comment by talhagithub** [comment]
Hi @peterrei 

Thanks for your response. I upgraded from 10 to 11.8, is it possible to downgrade the existing 11.8 install?

Otherwise, I was thinking to export the data somehow and reimport into a fresh install.

**Comment by ifproject** [comment]
@peterrei

I confirm PID file is not created at all on my box after upgrading to 11.8

/etc/init.d/kaltura-batch restart
Stopping Batch Manager.... 
Killing Batch Manager with PID  and related workers	[    OK    ]
Starting Batch Manager.... 
Batch Manager started with PID 	[    OK    ]
[root@videohost ~]# vi /opt/kaltura/log/batch/batch.pid
[root@videohost ~]# ls -la /opt/kaltura/log/batch/batch.pid
ls: cannot access /opt/kaltura/log/batch/batch.pid: No such file or directory

**Comment by talhagithub** [comment]
**Update:**

I did a fresh CentOS 6 + Kaltura 11.8 installation and got the exact same error on the sanity check:

```
[kaltura_logo_animated_blue.flv - 0_ajkczmvu status] [FAILED, RC: 1] - [-.585997126]
[DWH cycle] [FAILED, RC: 255] - [52.436382316]
```

How do I install earlier version of Kaltura?

**Comment by jessp01** [comment]
All, 
I have just installed a fresh instance with 11.8.0 and had no issues. Considering that and the fact our CI system has also been successful in install it and all sanity test have passed, this is not a general bug in the version and I am closing this issue.

Any of you that have issues, please post them at forum.kaltura.org stating the following:
- CE version and Linux distro used
- Relevant lines from /opt/kaltura/log/kaltura_batch.log 

@talhagithub - in your particular case, I see:
PHP Warning:  file_put_contents(/batch.pid): failed to open stream: Permission denied in /opt/kaltura/app/batch/scheduler/KGenericScheduler.class.php on line 97

This is obviously wrong. If you open /opt/kaltura/app/batch/scheduler/KGenericScheduler.class.php  in line 97 you will see:
file_put_contents($pid, getmypid())
And $pid is set by:
$pid = $this->schedulerConfig->getPidFileDir() . '/batch.pid';

So, my educated guess is you have:
logDir                                                                                          = /

in your /opt/kaltura/app/configurations/batch/batch.ini
which in fact should be:
logDir  = /opt/kaltura/log/batch/

You can of course fix this manually but I suspect, if you have this issue, you probably have many other similar ones and you should just rerun the kaltura-config-all.sh script to fix them.

@ifproject - your issue is not the same as the issue described here, the only thing in common is that both are batch related issues and in @talhagithub, like I wrote, I believe the issue goes deeper.
I have also answered you in https://github.com/kaltura/platform-install-packages/issues/523

Thank you,
