### ISSUE TITLE
Kaltura audio player thumbnail not found

### ISSUE THREAD

**Issue by syedwaseemjan** [kaltura/platform-install-packages#611]
We have upgraded Kaltura from 10.0.1 to 13.0.1. After alot of problems we were able to make it run but now we have a small issue with one of our thumbnails. We are not getting the audio thumbnail  anymore. So either the file is missing on the server or we have some permission issue. I have tried to re-install **kaltura-html5lib** but nothing changed. I have run front-config also after updating html5lib. 
Our **/opt/kaltura/web** is a symlink to another folder located on a different drive **/home/kaltura/kaltura/web/**

Here is what we are getting
![wrong_thumbnail_audio](https://user-images.githubusercontent.com/10591478/30543916-2a06b154-9c9e-11e7-85b1-c85473146471.png)
This is what we should have
![right_thumbnail_audio](https://user-images.githubusercontent.com/10591478/30543925-30a9dedc-9c9e-11e7-988a-b2a221612ac9.png)

Here are the contents of **/home/kaltura/kaltura/web/**
```
drwxrwxr-x. 11 kaltura apache   4096 2017-09-14 05:35 content
drwxr-xr-x.  2 kaltura kaltura  4096 2017-08-15 06:50 control
drwxr-xr-x.  3 kaltura kaltura  4096 2017-09-14 05:41 dropfolders
drwxrwxr-x. 13 root    root     4096 2017-09-15 05:01 flash
drwxrwxr-x.  3 root    root     4096 2015-09-04 02:07 html5
drwxr-xr-x.  2 root    root    45056 2017-09-18 03:48 logs
drwxrwxr-x.  5 apache  kaltura  4096 2017-09-18 06:37 tmp
```

Some output from **kaltlog**
```
2017-09-18 08:31:24 [0.000344] [192.168.90.84] [1504947821] [85] [API] [kFileSyncUtils::getContentsByFileSync] INFO: file was not found locally [/opt/kaltura/web/content/templates/entry/data/kmc_template_playlist1.txt]
2017-09-18 08:31:24 [0.000739] [192.168.90.84] [1504947821] [86] [API] [kCoreException->__construct] ERR: exception 'kFileSyncException' with message 'Cannot find file on local disk [/opt/kaltura/web/content/templates/entry/data/kmc_template_playlist1.txt] for file sync [13]' in /opt/kaltura/app/alpha/apps/kaltura/lib/storage/kFileSyncUtils.class.php:77
Stack trace:
#0 /opt/kaltura/app/alpha/apps/kaltura/lib/storage/kFileSyncUtils.class.php(177): kFileSyncUtils::getContentsByFileSync(Object(FileSync), true, true, false)
--
#12 {main}
2017-09-18 08:31:24 [0.000678] [192.168.90.84] [1504947821] [87] [API] [KalturaFrontController->getExceptionObject] CRIT: exception 'kFileSyncException' with message 'Cannot find file on local disk [/opt/kaltura/web/content/templates/entry/data/kmc_template_playlist1.txt] for file sync [13]' in /opt/kaltura/app/alpha/apps/kaltura/lib/storage/kFileSyncUtils.class.php:77
Stack trace:
#0 /opt/kaltura/app/alpha/apps/kaltura/lib/storage/kFileSyncUtils.class.php(177): kFileSyncUtils::getContentsByFileSync(Object(FileSync), true, true, false)
--
]
2017-09-18 08:31:27 [0.001324] [192.168.90.84] [319345461] [4] [API] [KalturaDispatcher->dispatch] CRIT: exception 'Exception' with message 'Action does not exist!' in /opt/kaltura/app/infra/log/KalturaLog.php:74
Stack trace:
#0 /opt/kaltura/app/api_v3/lib/KalturaDispatcher.php(57): KalturaLog::crit('Action does not...')
--

2017-09-18 08:31:27 [0.001138] [192.168.90.84] [319345461] [5] [API] [KalturaFrontController->getExceptionObject] ERR: exception 'KalturaAPIException' with message 'Action "trackevent" does not exists for service "analytics"' in /opt/kaltura/app/api_v3/lib/KalturaDispatcher.php:58
Stack trace:
#0 /opt/kaltura/app/api_v3/lib/KalturaFrontController.php(113): KalturaDispatcher->dispatch('analytics', 'trackEvent', Array)
--
2017-09-18 08:31:28 [0.000343] [192.168.90.84] [243143399] [92] [PS2] [kFileSyncUtils::getReadyFileSyncForKey] NOTICE: FileSync was not found
2017-09-18 08:31:28 [0.000856] [192.168.90.84] [243143399] [93] [PS2] [kCoreException->__construct] ERR: exception 'kFileSyncException' with message 'no ready filesync on current DC' in /opt/kaltura/app/alpha/apps/kaltura/lib/myEntryUtils.class.php:841
Stack trace:
#0 /opt/kaltura/app/alpha/lib/model/entry.php(3440): myEntryUtils::resizeEntryImage(Object(entry), 100000, 560, 395, 1, 'ffffff', NULL, 0, 0, 0, 0, 0, -1, '-1', '-1')
--
2017-09-18 08:31:28 [0.000354] [192.168.90.84] [243143399] [101] [PS2] [kFileSyncUtils::getReadyFileSyncForKey] NOTICE: FileSync was not found
2017-09-18 08:31:28 [0.000455] [192.168.90.84] [243143399] [102] [PS2] [entry->getLocalThumbFilePath] ERR: exception 'Exception' with message 'No ready fileSync found on any DC.' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/alpha/lib/model/entry.php(3457): KalturaLog::err('No ready fileSy...')
--
#16 {main}
2017-09-18 08:31:28 [0.000485] [192.168.90.84] [243143399] [103] [PS2] [KExternalErrors::dieError] ERR: exception 'Exception' with message 'exiting on error 10 - missing thumbnail fileSync for entry' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/alpha/apps/kaltura/lib/KExternalErrors.class.php(134): KalturaLog::err('exiting on erro...')
--
2017-09-18 08:31:28 [0.000260] [30182447] [19] [BATCH] [kFileTransferMgr->fileExists] DEBUG: File does not exist
2017-09-18 08:31:28 [0.002509] [30182447] [20] [BATCH] [KAsyncDropFolderWatcher->freeExclusiveDropFolder] ERR: exception 'Exception' with message 'Error with folder id [2] - Failed to list files located in the  drop folder. Please verify drop folder path and/or listing permissions in physical drop folder path' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/plugins/drop_folder/batch/DropFolderWatcher/KAsyncDropFolderWatcher.class.php(105): KalturaLog::err('Error with fold...')
--
==> /opt/kaltura/log/batch/dropfolderwatcher-0-2017-09-18.log <==
2017-09-18 08:31:29 [0.000385] [30182447] [80] [BATCH] [KAsyncDropFolderWatcher->freeExclusiveDropFolder] ERR: exception 'Exception' with message 'Error with folder id [2] - Failed to list files located in the  drop folder. Please verify drop folder path and/or listing permissions in physical drop folder path' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/plugins/drop_folder/batch/DropFolderWatcher/KAsyncDropFolderWatcher.class.php(105): KalturaLog::err('Error with fold...')
--
==> /opt/kaltura/log/batch/dropfolderwatcher-0-2017-09-18.log <==
2017-09-18 08:31:29 [0.000427] [30182447] [140] [BATCH] [KAsyncDropFolderWatcher->freeExclusiveDropFolder] ERR: exception 'Exception' with message 'Error with folder id [2] - Failed to list files located in the  drop folder. Please verify drop folder path and/or listing permissions in physical drop folder path' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/plugins/drop_folder/batch/DropFolderWatcher/KAsyncDropFolderWatcher.class.php(105): KalturaLog::err('Error with fold...')
--
2017-09-18 08:31:29 [0.000258] [30182447] [199] [BATCH] [kFileTransferMgr->fileExists] DEBUG: File does not exist
2017-09-18 08:31:29 [0.000387] [30182447] [200] [BATCH] [KAsyncDropFolderWatcher->freeExclusiveDropFolder] ERR: exception 'Exception' with message 'Error with folder id [2] - Failed to list files located in the  drop folder. Please verify drop folder path and/or listing permissions in physical drop folder path' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/plugins/drop_folder/batch/DropFolderWatcher/KAsyncDropFolderWatcher.class.php(105): KalturaLog::err('Error with fold...')
--
2017-09-18 08:31:29 [0.000361] [192.168.90.84] [556704776] [109] [PS2] [kFileSyncUtils::getReadyFileSyncForKey] NOTICE: FileSync was not found
2017-09-18 08:31:29 [0.000891] [192.168.90.84] [556704776] [110] [PS2] [kCoreException->__construct] ERR: exception 'kFileSyncException' with message 'no ready filesync on current DC' in /opt/kaltura/app/alpha/apps/kaltura/lib/myEntryUtils.class.php:841
Stack trace:
#0 /opt/kaltura/app/alpha/lib/model/entry.php(3440): myEntryUtils::resizeEntryImage(Object(entry), 100000, 100, 0, 1, 'ffffff', NULL, 0, 0, 0, 0, 0, -1, '-1', '100')
--
2017-09-18 08:31:29 [0.000333] [192.168.90.84] [556704776] [118] [PS2] [kFileSyncUtils::getReadyFileSyncForKey] NOTICE: FileSync was not found
2017-09-18 08:31:29 [0.000451] [192.168.90.84] [556704776] [119] [PS2] [entry->getLocalThumbFilePath] ERR: exception 'Exception' with message 'No ready fileSync found on any DC.' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/alpha/lib/model/entry.php(3457): KalturaLog::err('No ready fileSy...')
--
==> /opt/kaltura/log/kaltura_prod.log <==
2017-09-18 08:31:29 [0.000498] [192.168.90.84] [556704776] [120] [PS2] [KExternalErrors::dieError] ERR: exception 'Exception' with message 'exiting on error 10 - missing thumbnail fileSync for entry' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/alpha/apps/kaltura/lib/KExternalErrors.class.php(134): KalturaLog::err('exiting on erro...')
--
2017-09-18 08:31:29 [0.000237] [30182447] [259] [BATCH] [kFileTransferMgr->fileExists] DEBUG: File does not exist
2017-09-18 08:31:29 [0.000336] [30182447] [260] [BATCH] [KAsyncDropFolderWatcher->freeExclusiveDropFolder] ERR: exception 'Exception' with message 'Error with folder id [2] - Failed to list files located in the  drop folder. Please verify drop folder path and/or listing permissions in physical drop folder path' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/plugins/drop_folder/batch/DropFolderWatcher/KAsyncDropFolderWatcher.class.php(105): KalturaLog::err('Error with fold...')
```

**libs** versions
```
kaltura-libmcrypt-2.5.7-5.x86_64
kaltura-ffmpeg-aux-2.1.3-1.x86_64
kaltura-libmcrypt-devel-2.5.7-5.x86_64
kaltura-monit-5.23.0-1.x86_64
kaltura-kmc-v5.42.3-2.noarch
kaltura-kdp3wrapper-v37.0-1.noarch
kaltura-kcw-1.0.0-6.noarch
kaltura-sphinx-2.2.1-21.x86_64
kaltura-front-13.1.0-1.noarch
kaltura-html5lib-v2.60-1.noarch
kaltura-libopencore-amr-0.1.2-2.x86_64
kaltura-sshpass-1.05-1.x86_64
kaltura-html5-studio-v2.1.0-1.noarch
kaltura-base-13.1.0-18.noarch
kaltura-clipapp-1.3-2.noarch
kaltura-flexwrapper-v1.2-1.noarch
kaltura-libmediainfo-0.7.61-7.x86_64
kaltura-pentaho-4.2.1-2.x86_64
kaltura-release-13.1.0-1.noarch
kaltura-server-13.1.0-1.noarch
kaltura-x264-0.140-2.20140104.x86_64
kaltura-a52dec-0.7.4-11.x86_64
kaltura-postinst-1.0.33-17.noarch
kaltura-librtmp-2.3-3.x86_64
kaltura-krecord-1.0.0-1.noarch
kaltura-kvpm-v1.0.6-1.noarch
kaltura-kclip-v1.1.2.1-2.noarch
kaltura-kdp3-v3.9.9-2.noarch
kaltura-mediainfo-0.7.61-7.x86_64
kaltura-dwh-12.14.0-1.noarch
kaltura-lame-3.99.5-3.x86_64
kaltura-ffmpeg-3.2-1.x86_64
kaltura-nginx-1.12.0-6.x86_64
kaltura-segmenter-1.0-2.x86_64
kaltura-kdp-v2.7.0-1.noarch
kaltura-kupload-v1.2.16-2.noarch
kaltura-kdpwrapper-v11.0-1.noarch
kaltura-widgets-1.0.0-8.noarch
kaltura-batch-13.1.0-1.noarch
```
Here are contents of **/opt/kaltura/web/content/templates/entry/data/**
```
drwxrwxr-x. 2 kaltura apache    4096 2017-09-18 08:52 kaldata
-rw-r--r--. 1 kaltura apache 2898373 2010-02-14 07:27 kaltura_logo_animated_black.flv
-rw-r--r--. 1 kaltura apache    3088 2015-12-29 10:51 kaltura_logo_animated_black.flv.ainfo
-rw-r--r--. 1 kaltura apache     254 2015-12-29 10:51 kaltura_logo_animated_black.flv.ametadata
-rw-r--r--. 1 kaltura apache    2400 2015-12-29 10:51 kaltura_logo_animated_black.flv.vinfo
-rw-r--r--. 1 kaltura apache    2846 2015-12-29 10:51 kaltura_logo_animated_black.flv.vmetadata
-rw-r--r--. 1 kaltura apache 2743980 2010-02-14 07:27 kaltura_logo_animated_blue.flv
-rw-r--r--. 1 kaltura apache 2615388 2010-02-14 07:27 kaltura_logo_animated_green.flv
-rw-r--r--. 1 kaltura apache 2490304 2010-02-14 07:27 kaltura_logo_animated_pink.flv
-rw-r--r--. 1 kaltura apache 2966138 2010-02-14 07:27 kaltura_logo_animated_red.flv
-rw-r--r--. 1 kaltura apache     257 2012-08-20 03:06 _KDP_RE_PL_100000.xml
-rw-r--r--. 1 kaltura apache  277975 2010-02-14 07:27 kmc_logo.flv
-rw-r--r--. 1 kaltura apache      50 2010-02-14 07:27 kmc_template_playlist1.txt
-rw-r--r--. 1 kaltura apache      50 2010-02-14 07:27 kmc_template_playlist2.txt
-rw-r--r--. 1 kaltura apache      54 2010-02-14 07:27 ManualPlaylistSample.txt
-rw-r--r--. 1 kaltura apache     258 2010-02-14 07:27 metadata_text.xml

```

**Comment by jessp01** [comment]
Does  /opt/kaltura/web/content/templates/entry/thumbnail/audio_thumb.jpg exist and is readable by the Apache user?

**Comment by syedwaseemjan** [comment]
Thumbnail folder wasn't there. Copying it from one of our other kaltura server solved the problem. 
Thanks a lot.

**Comment by jessp01** [comment]
You're welcome. From your attached log entries, I see you're missing additional files, for instance:
```
2017-09-18 08:31:24 [0.000344] [192.168.90.84] [1504947821] [85] [API] [kFileSyncUtils::getContentsByFileSync] INFO: file was not found locally [/opt/kaltura/web/content/templates/entry/data/kmc_template_playlist1.txt]
```
I suggest you make sure to copy /opt/kaltura/web/content in its entirety and of course, with the correct permissions.

**Comment by syedwaseemjan** [comment]
Ok but why does re-installing html5lib doesn't create these files ?

**Comment by jessp01** [comment]
Because they don't belong to the kaltura-html5lib package, they belong to kaltura-base.
You can use:
\# rpm -qf /path/to/file
or:
\# dpkg -S /path/to/file
to see what package owns a given file.

**Comment by syedwaseemjan** [comment]
ok I have reinstalled kaltura-base but why am I still getting those above errors in the logs files. There errors are apparently not effecting anything.

**Comment by jessp01** [comment]
When you say "these errors" what errors are you referring to? You had several different errors in your original post. Not all of them due to missing files...
Do you now have /opt/kaltura/web/content/templates/entry/data/kmc_template_playlist1.txt and /opt/kaltura/web/content/templates/entry/thumbnail/audio_thumb.jpg?

**Comment by syedwaseemjan** [comment]
I am not talking about the orignial post. I mentioned them in comments, let me paste them again here
```
2017-09-18 10:35:32 [0.000229] [745400894] [19] [BATCH] [kFileTransferMgr->fileExists] DEBUG: File does not exist
2017-09-18 10:35:32 [0.002557] [745400894] [20] [BATCH] [KAsyncDropFolderWatcher->freeExclusiveDropFolder] ERR: exception 'Exception' with message 'Error with folder id [2] - Failed to list files located in the  drop folder. Please verify drop folder path and/or listing permissions in physical drop folder path' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/plugins/drop_folder/batch/DropFolderWatcher/KAsyncDropFolderWatcher.class.php(105): KalturaLog::err('Error with fold...')
--
2017-09-18 10:35:32 [0.000250] [745400894] [79] [BATCH] [kFileTransferMgr->fileExists] DEBUG: File does not exist
2017-09-18 10:35:32 [0.000378] [745400894] [80] [BATCH] [KAsyncDropFolderWatcher->freeExclusiveDropFolder] ERR: exception 'Exception' with message 'Error with folder id [2] - Failed to list files located in the  drop folder. Please verify drop folder path and/or listing permissions in physical drop folder path' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/plugins/drop_folder/batch/DropFolderWatcher/KAsyncDropFolderWatcher.class.php(105): KalturaLog::err('Error with fold...')
--
2017-09-18 10:35:32 [0.000229] [745400894] [139] [BATCH] [kFileTransferMgr->fileExists] DEBUG: File does not exist
2017-09-18 10:35:32 [0.000336] [745400894] [140] [BATCH] [KAsyncDropFolderWatcher->freeExclusiveDropFolder] ERR: exception 'Exception' with message 'Error with folder id [2] - Failed to list files located in the  drop folder. Please verify drop folder path and/or listing permissions in physical drop folder path' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/plugins/drop_folder/batch/DropFolderWatcher/KAsyncDropFolderWatcher.class.php(105): KalturaLog::err('Error with fold...')
--
2017-09-18 10:35:32 [0.000235] [745400894] [199] [BATCH] [kFileTransferMgr->fileExists] DEBUG: File does not exist
2017-09-18 10:35:32 [0.000338] [745400894] [200] [BATCH] [KAsyncDropFolderWatcher->freeExclusiveDropFolder] ERR: exception 'Exception' with message 'Error with folder id [2] - Failed to list files located in the  drop folder. Please verify drop folder path and/or listing permissions in physical drop folder path' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/plugins/drop_folder/batch/DropFolderWatcher/KAsyncDropFolderWatcher.class.php(105): KalturaLog::err('Error with fold...')
--
2017-09-18 10:35:33 [0.000280] [745400894] [259] [BATCH] [kFileTransferMgr->fileExists] DEBUG: File does not exist
2017-09-18 10:35:33 [0.000351] [745400894] [260] [BATCH] [KAsyncDropFolderWatcher->freeExclusiveDropFolder] ERR: exception 'Exception' with message 'Error with folder id [2] - Failed to list files located in the  drop folder. Please verify drop folder path and/or listing permissions in physical drop folder path' in /opt/kaltura/app/infra/log/KalturaLog.php:83

```

**Comment by jessp01** [comment]
That's something else.
You apparently have several drop folders configured and the path you specified for them does not exist on the disk or the 'kaltura' user cannot read from.
You can get a listing of them with:
```
mysql> select id,name,path,status from drop_folder;
```
From the log, it seems the complaint is about drop_folder.id 2.

**Comment by syedwaseemjan** [comment]
I have these entries in my drop_folder table
```
| id | name          | path                                                   | status |
+----+---------------+--------------------------------------------------------+--------+
|  1 | monitor local | /opt/kaltura/web/dropfolders/monitor                   |      1 |
|  2 | sanity_drop   | /tmp/sanity-drop-04-06-09-05-ktsqa2015                 |      3 |
|  3 | sanity_drop   | /tmp/sanity-drop-13-06-09-15-ktsqa2015                 |      2 |
|  4 | sanity_drop   | /tmp/sanity-drop-14-03-09-11-newqa.kaltura.artstor.org |      2 
```
I emptied the tmp folder few days ago. Should I just remove these entries to get rid of these errors?

**Comment by jessp01** [comment]
As a general rule, I don't recommend setting up drop folders under /tmp since, during init, all files under /tmp are removed in most if not all, Linux distros.

From the name of the dropfolder [sanity_drop], I presume this was created as a test when running the kaltura-sanity.sh script. You probably stopped it in mid run so it didn't have the chance to delete the dropfolder. You can go into Admin Console->Publishers->The Publisher this drop folder was set for->Profiles->Drop Folders and remove it.

To get the Partner ID this drop folder is associated with:
```
mysql> select id,name,path,status,partner_id from drop_folder where id=2;
```

**Comment by syedwaseemjan** [comment]
Yep, that worked. Most of the errors have gone now. One other thing I have noticed is the default message for under process media. The message has changed after the update. Can we change it?
This is what we are getting now
![qa](https://user-images.githubusercontent.com/10591478/30586443-674654d8-9d49-11e7-9772-27618cd46e54.png)
This is what it was previously
![prod](https://user-images.githubusercontent.com/10591478/30586452-6eb63490-9d49-11e7-957f-0e20faaf67c7.png)
