### ISSUE TITLE
Kaltura Files Not Playing

### ISSUE THREAD

**Issue by syedwaseemjan** [kaltura/platform-install-packages#613]
Kaltura was working fine but I restored data from another DB, ran sphinx-reindex script, mounted a NAS drive where images were placed and  also rerun kaltura-config-all.sh. Most of the things seems to be working fine except when we click play button, kaltura shows the following error

```
==> /opt/kaltura/log/batch/kschedulehelper-0-2017-10-25.err.log <==
PHP Warning:  file_get_contents(/opt/kaltura/app/cache//batch/classMap.cache): failed to open stream: Permission denied in /opt/kaltura/app/infra/KAutoloader.php on line 415
PHP Class map could not be loaded from path [/opt/kaltura/app/cache//batch/classMap.cache] file permissions [0600]
--
==> /opt/kaltura/log/batch/validatelivemediaservers-0-2017-10-25.err.log <==
PHP Warning:  file_get_contents(/opt/kaltura/app/cache//batch/classMap.cache): failed to open stream: Permission denied in /opt/kaltura/app/infra/KAutoloader.php on line 415
PHP Class map could not be loaded from path [/opt/kaltura/app/cache//batch/classMap.cache] file permissions [0600]

```

```
==> /opt/kaltura/log/kaltura_api_v3.log <==
2017-10-25 09:30:39 [9.002845] [192.168.90.84] [714895628] [46] [API] [KExternalErrors::dieError] ERR: exception 'Exception' with message 'exiting on error 5 - required file was not found' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/alpha/apps/kaltura/lib/KExternalErrors.class.php(134): KalturaLog::err('exiting on erro...')
--
==> /opt/kaltura/log/kaltura_api_v3.log <==
2017-10-25 09:30:42 [9.001061] [192.168.90.84] [2046688387] [46] [API] [KExternalErrors::dieError] ERR: exception 'Exception' with message 'exiting on error 5 - required file was not found' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/alpha/apps/kaltura/lib/KExternalErrors.class.php(134): KalturaLog::err('exiting on erro...')
--
==> /opt/kaltura/log/kaltura_api_v3.log <==
2017-10-25 09:30:42 [9.000970] [192.168.90.84] [1179811999] [46] [API] [KExternalErrors::dieError] ERR: exception 'Exception' with message 'exiting on error 5 - required file was not found' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/alpha/apps/kaltura/lib/KExternalErrors.class.php(134): KalturaLog::err('exiting on erro...')
--
2017-10-25 09:31:00 [0.000223] [192.168.90.84] [812288274] [36] [PS2] [kFileUtils::dumpUrl] DEBUG: URL [http://192.168.90.105/p/101/sp/10100/serveFlavor/entryId/0_el2ta33r/v/2/flavorId/0_7xywlc35/forceproxy/true/name/a.mp4], 1 [1],  []
2017-10-25 09:31:00 [0.000427] [192.168.90.84] [812288274] [37] [PS2] [KExternalErrors::dieError] ERR: exception 'Exception' with message 'exiting on error 23 - proxied request is being looped back' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/alpha/apps/kaltura/lib/KExternalErrors.class.php(134): KalturaLog::err('exiting on erro...')

```
**Delivery_profile entries:**
```
mysql> select id,name,url,host_name from delivery_profile;
+------+------------------------------------------------+-------------------------------+----------------+
| id   | name                                           | url                           | host_name      |
+------+------------------------------------------------+-------------------------------+----------------+
| 1001 | Kaltura HLS segmentation                       | http://192.168.90.105:88/hls  | 192.168.90.105 |
| 1002 | Kaltura HDS segmentation                       | http://192.168.90.105:88/hds  | 192.168.90.105 |
| 1003 | Kaltura DASH segmentation                      | http://192.168.90.105:88/dash | 192.168.90.105 |
|  501 | Default HTTP Delivery Profile                  | http://192.168.90.105:80      | 192.168.90.105 |
|  500 | Default HTTP Delivery Profile                  | http://192.168.90.105:80      | 192.168.90.105 |
|  101 | Default HLS Live Delivery Profile              | NULL                          | NULL           |
|    1 | Default HD Network Live Delivery Profile       | NULL                          | NULL           |
|    2 | Default HDS Live Delivery Profile              | NULL                          | NULL           |
|  201 | Default RTMP Live Delivery Profile             | NULL                          | NULL           |
| 1004 | Default HLS Live Delivery Profile              | NULL                          | NULL           |
| 1005 | Default HLS Network Live Delivery Profile      | NULL                          | NULL           |
| 1006 | Default HD Network Live Delivery Profile       | NULL                          | NULL           |
| 1007 | Default HDS Live Delivery Profile              | NULL                          | NULL           |
| 1008 | Default RTMP Live Delivery Profile             | NULL                          | NULL           |
|  301 | Default MPEG-DASH Live Delivery Profile        | NULL                          | NULL           |
| 1009 | Default HLS To Multicast Live Delivery Profile | NULL                          | NULL           |
+------+------------------------------------------------+-------------------------------+----------------+

```
**Library Versions:**
```
[dev@sspilotkaltura ~]$ rpm -qa "kaltura*"
kaltura-libopencore-amr-0.1.2-2.x86_64
kaltura-sshpass-1.05-1.x86_64
kaltura-kdp3wrapper-v37.0-1.noarch
kaltura-kdp3-v3.9.9-2.noarch
kaltura-libmediainfo-0.7.61-7.x86_64
kaltura-segmenter-1.0-2.x86_64
kaltura-kmc-v5.42.3-2.noarch
kaltura-pentaho-4.2.1-2.x86_64
kaltura-libfaac-1.26-1.x86_64
kaltura-libmemcached-1.0.16-2.x86_64
kaltura-kvpm-v1.0.6-1.noarch
kaltura-flexwrapper-v1.2-1.noarch
kaltura-mediainfo-0.7.61-7.x86_64
kaltura-sphinx-2.2.1-21.x86_64
kaltura-postinst-1.0.33-17.noarch
kaltura-batch-13.1.0-1.noarch
kaltura-kupload-v1.2.16-2.noarch
kaltura-dwh-12.14.0-1.noarch
kaltura-release-13.3.0-1.noarch
kaltura-x264-0.140-2.20140104.x86_64
kaltura-a52dec-0.7.4-11.x86_64
kaltura-lame-3.99.5-3.x86_64
kaltura-kclip-v1.1.2.1-2.noarch
kaltura-kdpwrapper-v11.0-1.noarch
kaltura-kcw-1.0.0-6.noarch
kaltura-fdk-acc-0.1.3-1.x86_64
kaltura-mencoder-3.4.6-9.x86_64
kaltura-html5-studio-v2.1.0-1.noarch
kaltura-monit-5.23.0-1.x86_64
kaltura-base-13.1.0-18.noarch
kaltura-ffmpeg-3.2-1.x86_64
kaltura-front-13.1.0-1.noarch
kaltura-clipapp-1.3-2.noarch
kaltura-server-13.1.0-1.noarch
kaltura-libass-0.9.11-2.x86_64
kaltura-libmcrypt-2.5.7-5.x86_64
kaltura-libmcrypt-devel-2.5.7-5.x86_64
kaltura-krecord-1.0.0-1.noarch
kaltura-kdp-v2.7.0-1.noarch
kaltura-widgets-1.0.0-8.noarch
kaltura-librtmp-2.3-3.x86_64
kaltura-html5lib-v2.60-1.noarch
kaltura-ffmpeg-aux-2.1.3-1.x86_64
kaltura-nginx-1.12.0-6.x86_64
kaltura-red5-1.0.6-1.x86_64

```

**Comment by syedwaseemjan** [comment]
Well I debugged it and turned out that some of the file were missing from /opt/kaltura/web/content/entry/data during NAS mount. Thanks anyway
