### ISSUE TITLE
Kaltura Files not processing after moving to new db and storage

### ISSUE THREAD

**Issue by faheemziker** [kaltura/platform-install-packages#622]
we have changed our database from older kaltura server to new kaltura server with all the files
now i am facing issue when i just import the file using api

<img width="1541" alt="screen shot 2018-01-07 at 5 10 34 am" src="https://user-images.githubusercontent.com/1622762/34645223-7abf4b2a-f369-11e7-8c86-b69aa3540d2a.png">

i get these errors from kaltlog

2018-01-06 19:00:33 [0.000403] [192.168.26.115] [1534260320] [25] [API] [KalturaStatement->execute] DEBUG: Sql took - 0.00025296211242676 seconds
2018-01-06 19:00:33 [0.000646] [192.168.26.115] [1534260320] [26] [API] [KalturaFrontController->getExceptionObject] ERR: exception ‘KalturaAPIException’ with message ‘The usage of feature [contentDistribution] is forbidden’ in /opt/kaltura/app/plugins/content_distribution/services/EntryDistributionService.php:17
Stack trace:
#0 /opt/kaltura/app/api_v3/lib/reflection/KalturaActionReflector.php(255): EntryDistributionService->initService(‘contentdistribu…’, ‘entryDistributi…’, ‘list’)
2018-01-06 19:00:34 [0.000163] [192.168.90.84] [201400468] [41] [PS2] [kFileSyncUtils::getReadyFileSyncForKey] NOTICE: FileSync was not found
2018-01-06 19:00:34 [0.000470] [192.168.90.84] [201400468] [42] [PS2] [KExternalErrors::dieError] ERR: exception ‘Exception’ with message ‘exiting on error 11 - processing capture thumbnail’ in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/alpha/apps/kaltura/lib/KExternalErrors.class.php(134): KalturaLog::err(‘exiting on erro…’)

**Comment by jessp01** [comment]
Closing this in favour of https://forum.kaltura.org/t/kaltura-file-not-processing-after-moving-to-new-db-and-storage/7864/3. Let's continue the discussion there.
