### ISSUE TITLE
kaltura-nginx install error libvpx.so problem

### ISSUE THREAD

**Issue by guidtz** [kaltura/platform-install-packages#642]
- [ ] I've read the [guidelines for Contributing to Kaltura Projects](https://github.com/kaltura/platform-install-packages/blob/master/CONTRIBUTING.md)
- [ ] I've read the [installation guides](https://github.com/kaltura/platform-install-packages#documentation-and-guides) and [troubleshooting FAQ](https://github.com/kaltura/platform-install-packages/blob/master/doc/kaltura-packages-faq.md)
- [ ] This is not a support request or question that should be posted on the [Kaltura forum](https://forum.kaltura.org) 

## Bug report

**Please provide steps to reproduce, including errors from /opt/kaltura/log/kaltura_api_v3.log, /opt/kaltura/log/kaltura_apache_errors*log and /opt/kaltura/log/kaltura_prod.log:**

**Linux distribution name and version:**
Debian Jessie

**Are you using the RPM or deb packages?**
- [ ] deb

**For deb based systems:**
```
# dpkg -l "kaltura-*"
ii  kaltura-base                         14.7.0-2                all                     Kaltura Open Source Video Platform
ii  kaltura-batch                        14.7.0-1                all                     Kaltura Open Source Video Platform - batch server
ii  kaltura-clipapp                      1.3-1+b2                all                     Kaltura Video Presentations Manager
ii  kaltura-db                           14.4.0-1                all                     Kaltura Open Source Video Platform - batch server
ii  kaltura-dwh                          12.14.0-1+b1            amd64                   Kaltura Open Source Video Platform - Analytics
ii  kaltura-ffmpeg                       4.0.2-1+b5              amd64                   
ii  kaltura-ffmpeg-aux                   2.1.3-1                 amd64                   
ii  kaltura-flexwrapper                  1.2-1+b1                all                     Kaltura Video Presentations Manager
ii  kaltura-front                        14.7.0-1                all                     Kaltura Open Source Video Platform - frontend server
ii  kaltura-html5-studio                 2.2.1-1                 all                     Kaltura Open Source Video Platform - frontend server
ii  kaltura-html5lib                     2.72-1                  all                     Kaltura Open Source Video Platform - HTML5 player
ii  kaltura-kclip                        1.1.2.1-1               all                     Kaltura Video Presentations Manager
ii  kaltura-kcw                          2.2.4-1+b3              all                     Kalture Contribution Wizard
ii  kaltura-kdp                          2.7.0-1                 all                     Kaltura Dynamic Player
ii  kaltura-kdp3                         3.9.9-1+b3              amd64                   Kaltura Dynamic Player
ii  kaltura-kdp3wrapper                  37-1                    all                     KDP3 Wrapper
ii  kaltura-kdpwrapper                   11-1                    all                     KDP Wrapper
ii  kaltura-kmc                          5.43.13-9               all                     Kaltura Management Console
ii  kaltura-kmcng                        5.4.2-1                 all                     Kaltura Management Console
ii  kaltura-krecord                      1.7-1                   all                     Kaltura kRecord - used for recording from web cam
ii  kaltura-kupload                      1.2.16-1                all                     Kaltura kupload widget
un  kaltura-libapache2-mod-php7          <aucune>                <aucune>                (aucune description n'est disponible)
iF  kaltura-nginx                        1.14.0-3                amd64                   Nginx web/proxy server - for Kaltura
ii  kaltura-pentaho                      4.2.1+b2                amd64                   Pentaho Open Source Data Integration Community Edition (CE).
un  kaltura-php7-apcu                    <aucune>                <aucune>                (aucune description n'est disponible)
un  kaltura-php7-cli                     <aucune>                <aucune>                (aucune description n'est disponible)
un  kaltura-php7-curl                    <aucune>                <aucune>                (aucune description n'est disponible)
un  kaltura-php7-gd                      <aucune>                <aucune>                (aucune description n'est disponible)
un  kaltura-php7-gmp                     <aucune>                <aucune>                (aucune description n'est disponible)
un  kaltura-php7-mcrypt                  <aucune>                <aucune>                (aucune description n'est disponible)
un  kaltura-php7-memcache                <aucune>                <aucune>                (aucune description n'est disponible)
un  kaltura-php7-mysql                   <aucune>                <aucune>                (aucune description n'est disponible)
un  kaltura-php7-ssh2                    <aucune>                <aucune>                (aucune description n'est disponible)
un  kaltura-php7-xsl                     <aucune>                <aucune>                (aucune description n'est disponible)
ii  kaltura-postinst                     1.0.33-3+b9             all                     Kaltura Open Source Video Platform
ii  kaltura-sphinx                       2.2.1-4+b3              amd64                   Sphinx full-text search server - for Kaltura
ii  kaltura-widgets                      14.1.0-1                all                     Kaltura Open Source Video Platform - widgets meta package
```

**Is this an all in one instance [single server] or a cluster?**
- [ ] All in one

**If applicable, please provide the MySQL version**
```
ii  mysql-server-5.5                  5.5.62-0+deb8u1                    amd64        MySQL database server binaries and system database setup
ii  mysql-server-core-5.5             5.5.62-0+deb8u1                    amd64        MySQL database server binaries
```

**If you're having an issue with a specific media asset, please provide a link from which it can be downloaded/played:**

Error when kaltura-nginx installation process : 
```
0 mis à jour, 0 nouvellement installés, 0 à enlever et 2 non mis à jour.
1 partiellement installés ou enlevés.
Après cette opération, 0 o d'espace disque supplémentaires seront utilisés.
Paramétrage de kaltura-nginx (1.14.0-3) ...
mkdir: opérande manquant
Saisissez « mkdir --help » pour plus d'informations.
Job for kaltura-nginx.service failed. See 'systemctl status kaltura-nginx.service' and 'journalctl -xn' for details.
invoke-rc.d: initscript kaltura-nginx, action "restart" failed.
dpkg: erreur de traitement du paquet kaltura-nginx (--configure) :
 le sous-processus script post-installation installé a retourné une erreur de sortie d'état 1
Traitement des actions différées (« triggers ») pour libc-bin (2.19-18+deb8u10) ...
Des erreurs ont été rencontrées pendant l'exécution :
 kaltura-nginx
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Error in journalctl : 
```
-- L'unité (unit) kaltura-nginx.service a commencé à démarrer.
nov. 14 10:19:07 ping-kaltura kaltura-nginx[3608]: Starting nginx: /opt/kaltura/nginx/sbin/nginx: error while loading shared libraries: libvpx.so.5: cannot open shared o
nov. 14 10:19:07 ping-kaltura systemd[1]: kaltura-nginx.service: control process exited, code=exited status=127
```

Thanks

**Comment by jessp01** [comment]
Hi @guidtz,

This is interesting because libvpx.so.5 is provided by the `libvpx5` package which is declared as a dep in kaltura-ffmpeg, which kaltura-nginx depends on.

For reference:
```sh
# dpkg -l kaltura-ffmpeg
ii  kaltura-ffmpeg               4.0.2-1+b5          amd64

# aptitude show kaltura-ffmpeg|grep libvpx5
         libva-x11-1, libvpx1 | libvpx3 | *libvpx5*, libxvidcore4, libvorbis0a,

# aptitude show kaltura-nginx|grep kaltura-ffmpeg
PreDepends: dpkg (>= 1.15.7.2~), kaltura-ffmpeg

# aptitude why kaltura-ffmpeg
i   kaltura-nginx PreDepends kaltura-ffmpeg
```
Or, in short:
```sh
# aptitude why libvpx5
i   kaltura-nginx  PreDepends kaltura-ffmpeg             
i A kaltura-ffmpeg Depends    libvpx1 | libvpx3 | libvpx5
```

Can you try to manually install the `libvpx5` package and see whether there are issues?

Thanks,

**Comment by guidtz** [comment]
I install manualy libvpx5 : 

```
# apt-get install why libvpx5
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
Le paquet suivant a été installé automatiquement et n'est plus nécessaire :
  libuuid-perl
Veuillez utiliser « apt-get autoremove » pour le supprimer.
Les paquets supplémentaires suivants seront installés : 
  alt-ergo aspell aspell-en binutils camlp4 coq coq-theories coqide cpp cpp-4.9 dbus-x11 dictionaries-common emacsen-common enchant file frama-c-base gcc gcc-4.9
  gconf-service gconf2 gconf2-common gnome-mime-data hunspell-en-us ledit libart-2.0-2 libasan1 libaspell15 libatomic1 libavahi-glib1 libbonobo2-0 libbonobo2-common
  libbonoboui2-0 libbonoboui2-common libc-dev-bin libc6-dev libcanberra0 libcilkrts5 libcloog-isl4 libcoq-ocaml libenchant1c2a libfindlib-ocaml libfindlib-ocaml-dev
  libgail18 libgcc-4.9-dev libgconf-2-4 libglade2-0 libgnome-2-0 libgnome-keyring-common libgnome-keyring0 libgnome2-0 libgnome2-bin libgnome2-common libgnomecanvas2-0
  libgnomecanvas2-common libgnomeui-0 libgnomeui-common libgnomevfs2-0 libgnomevfs2-common libgnomevfs2-extra libgtksourceview2.0-0 libgtksourceview2.0-common
  libgtkspell0 libhunspell-1.3-0 libisl10 libitm1 liblablgtk2-gnome-ocaml liblablgtk2-ocaml liblablgtksourceview2-ocaml liblsan0 libmpc3 libmpfr4 libncurses5-dev
  libocamlgraph-ocaml-dev liborbit-2-0 libquadmath0 libtdb1 libtinfo-dev libtsan0 libubsan0 libwhy-coq libzarith-ocaml linux-libc-dev make manpages-dev ocaml-base-nox
  ocaml-compiler-libs ocaml-findlib ocaml-interp ocaml-nox
Paquets suggérés :
  aspell-doc spellutils binutils-doc proofgeneral libcoq-ocaml-dev coq-doc cpp-doc gcc-4.9-locales wordlist gcc-multilib autoconf automake libtool flex bison gdb
  gcc-doc gcc-4.9-multilib gcc-4.9-doc libgcc1-dbg libgomp1-dbg libitm1-dbg libatomic1-dbg libasan1-dbg liblsan0-dbg libtsan0-dbg libubsan0-dbg libcilkrts5-dbg
  libquadmath0-dbg gconf-defaults-service hunspell openoffice.org-hunspell openoffice.org-core libbonobo2-bin glibc-doc libcanberra-gtk0 libcanberra-pulse
  libenchant-voikko gnome-keyring desktop-base gnome-icon-theme libgnomevfs2-bin ncurses-doc make-doc ocaml-findlib-wizard ocaml-doc tuareg-mode ocaml-mode
Les NOUVEAUX paquets suivants seront installés :
  alt-ergo aspell aspell-en binutils camlp4 coq coq-theories coqide cpp cpp-4.9 dbus-x11 dictionaries-common emacsen-common enchant file frama-c-base gcc gcc-4.9
  gconf-service gconf2 gconf2-common gnome-mime-data hunspell-en-us ledit libart-2.0-2 libasan1 libaspell15 libatomic1 libavahi-glib1 libbonobo2-0 libbonobo2-common
  libbonoboui2-0 libbonoboui2-common libc-dev-bin libc6-dev libcanberra0 libcilkrts5 libcloog-isl4 libcoq-ocaml libenchant1c2a libfindlib-ocaml libfindlib-ocaml-dev
  libgail18 libgcc-4.9-dev libgconf-2-4 libglade2-0 libgnome-2-0 libgnome-keyring-common libgnome-keyring0 libgnome2-0 libgnome2-bin libgnome2-common libgnomecanvas2-0
  libgnomecanvas2-common libgnomeui-0 libgnomeui-common libgnomevfs2-0 libgnomevfs2-common libgnomevfs2-extra libgtksourceview2.0-0 libgtksourceview2.0-common
  libgtkspell0 libhunspell-1.3-0 libisl10 libitm1 liblablgtk2-gnome-ocaml liblablgtk2-ocaml liblablgtksourceview2-ocaml liblsan0 libmpc3 libmpfr4 libncurses5-dev
  libocamlgraph-ocaml-dev liborbit-2-0 libquadmath0 libtdb1 libtinfo-dev libtsan0 libubsan0 libvpx5 libwhy-coq libzarith-ocaml linux-libc-dev make manpages-dev
  ocaml-base-nox ocaml-compiler-libs ocaml-findlib ocaml-interp ocaml-nox why
0 mis à jour, 91 nouvellement installés, 0 à enlever et 2 non mis à jour.
1 partiellement installés ou enlevés.
Il est nécessaire de prendre 121 Mo dans les archives.
Après cette opération, 603 Mo d'espace disque supplémentaires seront utilisés.
```

And now another error with kaltura-nginx : 

```
nov. 14 14:38:08 ping-kaltura kaltura-nginx[20208]: Starting nginx: /opt/kaltura/nginx/sbin/nginx: error while loading shared libraries: libx264.so.142: cannot open shar
nov. 14 14:38:08 ping-kaltura systemd[1]: kaltura-nginx.service: control process exited, code=exited status=127
```

**Comment by guidtz** [comment]
After that : 
```
apt-get install	libx264-dev
```
```
apt-get install libass-dev
```
Another error  
```
nov. 14 14:43:42 ping-kaltura kaltura-nginx[23532]: Starting nginx: nginx: [emerg] invalid number of arguments in "alias" directive in /opt/kaltura/nginx/conf/server.con
nov. 14 14:43:42 ping-kaltura kaltura-nginx[23532]: nginx: configuration file /opt/kaltura/nginx/conf/nginx.conf test failed
```

All alias lines :
```
		location /pd/ {
			alias ;
```

**Comment by jessp01** [comment]
Hi @guidtz,

Unlike the issue with libvpx5 which IS correctly declared as a dep [see my last response], the issue you encountered with the missing libx264-142 dep is a bug. I just fixed that here:
https://github.com/kaltura/platform-install-packages/commit/09efaa73d914904d82d6edc0df2aea4ae2d65daf
Same for libass5, see:
https://github.com/kaltura/platform-install-packages/commit/3b23828f1c883fc0b22e36a8a25fd1b0278df01f

BTW, unless you intend to do development work, there's no need to install the `-dev` packages. These include headers and archive files. It's enough to install `libass5` and `libx264-142`. 

Your current issue stems from the fact that during the kaltura-nginx postinst `configure` stage, when you were prompted for the different values, you sent an empty string and so, the Nginx config is invalid.

You may edit the conf file directly and provide the correct values or else reconfigure your package with either:
```sh
# apt-get install -f
```
or:
```sh
# dpkg-reconfigure kaltura-nginx
```

Cheers,

**Comment by jessp01** [comment]
Hi @guidtz - are we good now?

**Comment by guidtz** [comment]
hello I replay all install this morning ! I say you after

**Comment by guidtz** [comment]
Hello,
  I repeated all process install and I have two errors : 

Error kaltura-db :
./install_kaltura_all_in_1.sh
continue installation

Error kaltura-nginx :
apt-get install why libvpx5 libx264-dev  libass-dev
./install_kaltura_all_in_1.sh

And now no errors in install process.

I have to test product now in ths week-end

**Comment by jessp01** [comment]
Hi @guidtz -

If you've experienced issues during the kaltura-db postinst phase the platform will almost definitely malfunction. What was the exact error?

**Comment by guidtz** [comment]
Hello, I'll go to rollback install. Wich logs do you wants with kaltura-db ?

**Comment by guidtz** [comment]
I have those errors : 

```
kaltura-db.postinst FAILED with: 32186 on line 231

Archving logs to /opt/kaltura/log/log_20_11_18_11_28.tar.gz...
dpkg: erreur de traitement du paquet kaltura-db (--configure) :
 le sous-processus script post-installation installé a retourné une erreur de sortie d'état 11
Des erreurs ont été rencontrées pendant l'exécution :
 kaltura-db
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by guidtz** [comment]
Ok I think there is a problem, my installation is behind a proxy ssl and in local is in http : 

```
Queuing action [userRole.add]
Queuing action [user.add]
Executing multirequest
service url: [http://kal2.mondomaine.com]
curl: http://kal2.mondomaine.com/api_v3/service/multirequest
post: {"format":"3","ignoreNull":true,"clientTag":"php5:18-11-20","apiVersion":"14.7.0","0":{"service":"userrole","action":"add","userRole":{"objectType":"KalturaUserRole","name":"System Administrator","systemName":"System Administrator","description":"System Administrator","status":"1","permissionNames":"*","tags":"admin_console"},"ks":"MWIzNjBmNDc3MjdmMjQxNjZmYjMxNTZmNDc1YWM2YWNhOWYzODI5MnwtMjstMjsxNTQyNzk2MTMzOzI7MjQ5NzY7Ow=="},"1":{"service":"user","action":"add","user":{"objectType":"KalturaUser","id":"myemail","screenName":"myemail","fullName":"Kaltura Administrator","email":"myemail","status":"1","password":"yohs!oa0Oph9","isAdmin":"1","roleIds":"{1:result:id}","allowedPartnerIds":"*"},"ks":"MWIzNjBmNDc3MjdmMjQxNjZmYjMxNTZmNDc1YWM2YWNhOWYzODI5MnwtMjstMjsxNTQyNzk2MTMzOzI7MjQ5NzY7Ow=="},"kalsig":"b3b487ca9e7ac6116dd121db0252f2ff"}
result (serialized): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://kal2.mondomaine.com/api_v3/service/multirequest">here</a>.</p>
</body></html>

PHP Fatal error:  Uncaught exception 'KalturaClientException' with message 'failed to unserialize server result
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://kal2.mondomaine.com/api_v3/service/multirequest">here</a>.</p>
</body></html>
' in /opt/kaltura/app/tests/lib/KalturaClientBase.php:401
Stack trace:
#0 /opt/kaltura/app/tests/lib/KalturaClientBase.php(953): KalturaClientBase->doQueue()
#1 /opt/kaltura/app/tests/standAloneClient/exec.php(345): KalturaClientBase->doMultiRequest()
#2 {main}
  thrown in /opt/kaltura/app/tests/lib/KalturaClientBase.php on line 401
```

Perhaps add url in /etc/hosts ?

I'll go to test new version tommorrow.

**Comment by jessp01** [comment]
Hi @guidtz,

It's perfectly okay and even recommended to set up SSL offloading, which is what I think you've done. However, it seems as though the LB does not auto redirect from HTTP to HTTPs and therefore, the request never reaches the Kaltura API nodes [HTTP 302 is returned when requesting http://kal2.mondomaine.com/api_v3/service/multirequest]?

You should add an auto redirect rule if the protocol is not HTTPs but it is also recommended that you use https://kal2.mondomaine.com as your base Kaltura endpoint [service URL].

In case it helps, we do provide sample configurations for load balancing/SSL offloading with both HAProxy and Apache's mod_proxy, see here:
https://github.com/kaltura/platform-install-packages/blob/Naos-14.9.0/doc/load_balancing.md

**Comment by jessp01** [comment]
@guidtz - can this be closed? Thanks.

**Comment by jessp01** [comment]
Closing due to lack of response but feel free to reopen should you encounter additional issues.

**Comment by guidtz** [comment]
Hello @jessp01, sorry for delay but for now the project is in standby, so when It restart we come back to you.
