### ISSUE TITLE
Ubuntu 20.04 server-all-in-1 install error on kaltura-db.postinst FAILED with: 194956 on line 236

### ISSUE THREAD

**Issue by nyok92** [kaltura/platform-install-packages#697]
**The install script stop at:**

Dépaquetage de kaltura-db (15.10.0-1+b1) ...
Paramétrage de kaltura-db (15.10.0-1+b1) ...
Checking MySQL version..

CREATE USER kaltura;
CREATE USER etl@'%';
CREATE DATABASE kaltura;
CREATE DATABASE kaltura_sphinx_log;
CREATE DATABASE kalturadw;
CREATE DATABASE kalturadw_ds;
CREATE DATABASE kalturadw_bisources;
CREATE DATABASE kalturalog;
Checking connectivity to needed daemons...
Connectivity test passed:)
Cleaning cache..
Populating DB with data.. please wait..
Output for /opt/kaltura/app/deployment/base/scripts/installPlugins.php being logged into /opt/kaltura/log/installPlugins.log 
Output for /opt/kaltura/app/deployment/base/scripts/insertDefaults.php being logged into /opt/kaltura/log/insertDefaults.log 

kaltura-db.postinst FAILED with: 194956 on line 236

Archving logs to /opt/kaltura/log/log_10_03_21_11_59.tar.gz...
dpkg: erreur de traitement du paquet kaltura-db (--configure) :
 installed kaltura-db package post-installation script subprocess returned error exit status 11
Des erreurs ont été rencontrées pendant l'exécution :
 kaltura-db
E: Sub-process /usr/bin/dpkg returned an error code (1)

**This is the /opt/kaltura/log/installPlugins.log**

PHP Fatal error:  Uncaught Error: Call to undefined function mb_strcut() in /opt/kaltura/app/alpha/apps/kaltura/lib/model/ktagword.class.php:36
Stack trace:
#0 /opt/kaltura/app/alpha/apps/kaltura/lib/model/ktagword.class.php(68): ktagword::tagsListFromParagraph()
#1 /opt/kaltura/app/alpha/lib/model/entry.php(1196): ktagword::updateTags()
#2 /opt/kaltura/app/deployment/base/scripts/insertDefaults.php(216): entry->setTags()
#3 /opt/kaltura/app/deployment/base/scripts/insertDefaults.php(69): handleFile()
#4 /opt/kaltura/app/deployment/base/scripts/insertDefaults.php(23): handleDirectory()
#5 {main}
  thrown in /opt/kaltura/app/alpha/apps/kaltura/lib/model/ktagword.class.php on line 36

**Comment by binhhieu001** [comment]
Same issue with me, @jessp01 @lucaguindani please help on this. Thanks

**Comment by binhhieu001** [comment]
Hi @nyok92 

I've resolved this issue. Because missing the mbstring for php7.4, please try the command to install it and try again:

apt-get install php7.4-mbstring
